// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `metadata.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:laoflchdb.SchemaMeta)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SchemaMeta {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.SchemaMeta.schema_name)
    pub schema_name: ::std::string::String,
    // @@protoc_insertion_point(field:laoflchdb.SchemaMeta.next_auto_inc_table_id)
    pub next_auto_inc_table_id: u64,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.SchemaMeta.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SchemaMeta {
    fn default() -> &'a SchemaMeta {
        <SchemaMeta as ::protobuf::Message>::default_instance()
    }
}

impl SchemaMeta {
    pub fn new() -> SchemaMeta {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "schema_name",
            |m: &SchemaMeta| { &m.schema_name },
            |m: &mut SchemaMeta| { &mut m.schema_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "next_auto_inc_table_id",
            |m: &SchemaMeta| { &m.next_auto_inc_table_id },
            |m: &mut SchemaMeta| { &mut m.next_auto_inc_table_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SchemaMeta>(
            "SchemaMeta",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SchemaMeta {
    const NAME: &'static str = "SchemaMeta";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.schema_name = is.read_string()?;
                },
                16 => {
                    self.next_auto_inc_table_id = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.schema_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.schema_name);
        }
        if self.next_auto_inc_table_id != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.next_auto_inc_table_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.schema_name.is_empty() {
            os.write_string(1, &self.schema_name)?;
        }
        if self.next_auto_inc_table_id != 0 {
            os.write_uint64(2, self.next_auto_inc_table_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SchemaMeta {
        SchemaMeta::new()
    }

    fn clear(&mut self) {
        self.schema_name.clear();
        self.next_auto_inc_table_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SchemaMeta {
        static instance: SchemaMeta = SchemaMeta {
            schema_name: ::std::string::String::new(),
            next_auto_inc_table_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SchemaMeta {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SchemaMeta").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SchemaMeta {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SchemaMeta {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:laoflchdb.TableMeta)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TableMeta {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.TableMeta.table_id)
    pub table_id: u64,
    // @@protoc_insertion_point(field:laoflchdb.TableMeta.table_name)
    pub table_name: ::std::string::String,
    // @@protoc_insertion_point(field:laoflchdb.TableMeta.column_count)
    pub column_count: u32,
    // @@protoc_insertion_point(field:laoflchdb.TableMeta.next_auto_inc_column_id)
    pub next_auto_inc_column_id: u64,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.TableMeta.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TableMeta {
    fn default() -> &'a TableMeta {
        <TableMeta as ::protobuf::Message>::default_instance()
    }
}

impl TableMeta {
    pub fn new() -> TableMeta {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "table_id",
            |m: &TableMeta| { &m.table_id },
            |m: &mut TableMeta| { &mut m.table_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "table_name",
            |m: &TableMeta| { &m.table_name },
            |m: &mut TableMeta| { &mut m.table_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "column_count",
            |m: &TableMeta| { &m.column_count },
            |m: &mut TableMeta| { &mut m.column_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "next_auto_inc_column_id",
            |m: &TableMeta| { &m.next_auto_inc_column_id },
            |m: &mut TableMeta| { &mut m.next_auto_inc_column_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TableMeta>(
            "TableMeta",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TableMeta {
    const NAME: &'static str = "TableMeta";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.table_id = is.read_uint64()?;
                },
                18 => {
                    self.table_name = is.read_string()?;
                },
                24 => {
                    self.column_count = is.read_uint32()?;
                },
                32 => {
                    self.next_auto_inc_column_id = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.table_id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.table_id);
        }
        if !self.table_name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.table_name);
        }
        if self.column_count != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.column_count);
        }
        if self.next_auto_inc_column_id != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.next_auto_inc_column_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.table_id != 0 {
            os.write_uint64(1, self.table_id)?;
        }
        if !self.table_name.is_empty() {
            os.write_string(2, &self.table_name)?;
        }
        if self.column_count != 0 {
            os.write_uint32(3, self.column_count)?;
        }
        if self.next_auto_inc_column_id != 0 {
            os.write_uint64(4, self.next_auto_inc_column_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TableMeta {
        TableMeta::new()
    }

    fn clear(&mut self) {
        self.table_id = 0;
        self.table_name.clear();
        self.column_count = 0;
        self.next_auto_inc_column_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TableMeta {
        static instance: TableMeta = TableMeta {
            table_id: 0,
            table_name: ::std::string::String::new(),
            column_count: 0,
            next_auto_inc_column_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TableMeta {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TableMeta").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TableMeta {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TableMeta {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:laoflchdb.ColumnMeta)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ColumnMeta {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.ColumnMeta.table_id)
    pub table_id: u64,
    // @@protoc_insertion_point(field:laoflchdb.ColumnMeta.column_id)
    pub column_id: u64,
    // @@protoc_insertion_point(field:laoflchdb.ColumnMeta.column_name)
    pub column_name: ::std::string::String,
    // @@protoc_insertion_point(field:laoflchdb.ColumnMeta.column_type)
    pub column_type: ::protobuf::EnumOrUnknown<ColumnType>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.ColumnMeta.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ColumnMeta {
    fn default() -> &'a ColumnMeta {
        <ColumnMeta as ::protobuf::Message>::default_instance()
    }
}

impl ColumnMeta {
    pub fn new() -> ColumnMeta {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "table_id",
            |m: &ColumnMeta| { &m.table_id },
            |m: &mut ColumnMeta| { &mut m.table_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "column_id",
            |m: &ColumnMeta| { &m.column_id },
            |m: &mut ColumnMeta| { &mut m.column_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "column_name",
            |m: &ColumnMeta| { &m.column_name },
            |m: &mut ColumnMeta| { &mut m.column_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "column_type",
            |m: &ColumnMeta| { &m.column_type },
            |m: &mut ColumnMeta| { &mut m.column_type },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ColumnMeta>(
            "ColumnMeta",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ColumnMeta {
    const NAME: &'static str = "ColumnMeta";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.table_id = is.read_uint64()?;
                },
                16 => {
                    self.column_id = is.read_uint64()?;
                },
                26 => {
                    self.column_name = is.read_string()?;
                },
                32 => {
                    self.column_type = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.table_id != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.table_id);
        }
        if self.column_id != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.column_id);
        }
        if !self.column_name.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.column_name);
        }
        if self.column_type != ::protobuf::EnumOrUnknown::new(ColumnType::COLUMN_TYPE_STRING) {
            my_size += ::protobuf::rt::int32_size(4, self.column_type.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.table_id != 0 {
            os.write_uint64(1, self.table_id)?;
        }
        if self.column_id != 0 {
            os.write_uint64(2, self.column_id)?;
        }
        if !self.column_name.is_empty() {
            os.write_string(3, &self.column_name)?;
        }
        if self.column_type != ::protobuf::EnumOrUnknown::new(ColumnType::COLUMN_TYPE_STRING) {
            os.write_enum(4, ::protobuf::EnumOrUnknown::value(&self.column_type))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ColumnMeta {
        ColumnMeta::new()
    }

    fn clear(&mut self) {
        self.table_id = 0;
        self.column_id = 0;
        self.column_name.clear();
        self.column_type = ::protobuf::EnumOrUnknown::new(ColumnType::COLUMN_TYPE_STRING);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ColumnMeta {
        static instance: ColumnMeta = ColumnMeta {
            table_id: 0,
            column_id: 0,
            column_name: ::std::string::String::new(),
            column_type: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ColumnMeta {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ColumnMeta").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ColumnMeta {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ColumnMeta {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:laoflchdb.ColumnType)
pub enum ColumnType {
    // @@protoc_insertion_point(enum_value:laoflchdb.ColumnType.COLUMN_TYPE_STRING)
    COLUMN_TYPE_STRING = 0,
    // @@protoc_insertion_point(enum_value:laoflchdb.ColumnType.COLUMN_TYPE_INT64)
    COLUMN_TYPE_INT64 = 1,
    // @@protoc_insertion_point(enum_value:laoflchdb.ColumnType.COLUMN_TYPE_BYTES)
    COLUMN_TYPE_BYTES = 2,
    // @@protoc_insertion_point(enum_value:laoflchdb.ColumnType.COLUMN_TYPE_FLOAT)
    COLUMN_TYPE_FLOAT = 3,
    // @@protoc_insertion_point(enum_value:laoflchdb.ColumnType.COLUMN_TYPE_LIST)
    COLUMN_TYPE_LIST = 4,
    // @@protoc_insertion_point(enum_value:laoflchdb.ColumnType.COLUMN_TYPE_IMAGE)
    COLUMN_TYPE_IMAGE = 5,
}

impl ::protobuf::Enum for ColumnType {
    const NAME: &'static str = "ColumnType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ColumnType> {
        match value {
            0 => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_STRING),
            1 => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_INT64),
            2 => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_BYTES),
            3 => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_FLOAT),
            4 => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_LIST),
            5 => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_IMAGE),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ColumnType> {
        match str {
            "COLUMN_TYPE_STRING" => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_STRING),
            "COLUMN_TYPE_INT64" => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_INT64),
            "COLUMN_TYPE_BYTES" => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_BYTES),
            "COLUMN_TYPE_FLOAT" => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_FLOAT),
            "COLUMN_TYPE_LIST" => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_LIST),
            "COLUMN_TYPE_IMAGE" => ::std::option::Option::Some(ColumnType::COLUMN_TYPE_IMAGE),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ColumnType] = &[
        ColumnType::COLUMN_TYPE_STRING,
        ColumnType::COLUMN_TYPE_INT64,
        ColumnType::COLUMN_TYPE_BYTES,
        ColumnType::COLUMN_TYPE_FLOAT,
        ColumnType::COLUMN_TYPE_LIST,
        ColumnType::COLUMN_TYPE_IMAGE,
    ];
}

impl ::protobuf::EnumFull for ColumnType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ColumnType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ColumnType {
    fn default() -> Self {
        ColumnType::COLUMN_TYPE_STRING
    }
}

impl ColumnType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ColumnType>("ColumnType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0emetadata.proto\x12\tlaoflchdb\"a\n\nSchemaMeta\x12\x1f\n\x0bschema\
    _name\x18\x01\x20\x01(\tR\nschemaName\x122\n\x16next_auto_inc_table_id\
    \x18\x02\x20\x01(\x04R\x12nextAutoIncTableId\"\x9e\x01\n\tTableMeta\x12\
    \x19\n\x08table_id\x18\x01\x20\x01(\x04R\x07tableId\x12\x1d\n\ntable_nam\
    e\x18\x02\x20\x01(\tR\ttableName\x12!\n\x0ccolumn_count\x18\x03\x20\x01(\
    \rR\x0bcolumnCount\x124\n\x17next_auto_inc_column_id\x18\x04\x20\x01(\
    \x04R\x13nextAutoIncColumnId\"\x9d\x01\n\nColumnMeta\x12\x19\n\x08table_\
    id\x18\x01\x20\x01(\x04R\x07tableId\x12\x1b\n\tcolumn_id\x18\x02\x20\x01\
    (\x04R\x08columnId\x12\x1f\n\x0bcolumn_name\x18\x03\x20\x01(\tR\ncolumnN\
    ame\x126\n\x0bcolumn_type\x18\x04\x20\x01(\x0e2\x15.laoflchdb.ColumnType\
    R\ncolumnType*\x96\x01\n\nColumnType\x12\x16\n\x12COLUMN_TYPE_STRING\x10\
    \0\x12\x15\n\x11COLUMN_TYPE_INT64\x10\x01\x12\x15\n\x11COLUMN_TYPE_BYTES\
    \x10\x02\x12\x15\n\x11COLUMN_TYPE_FLOAT\x10\x03\x12\x14\n\x10COLUMN_TYPE\
    _LIST\x10\x04\x12\x15\n\x11COLUMN_TYPE_IMAGE\x10\x05J\x98\x07\n\x06\x12\
    \x04\0\0\x1e\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\
    \x02\0\x12\n\n\n\x02\x04\0\x12\x04\x04\0\x07\x01\n\n\n\x03\x04\0\x01\x12\
    \x03\x04\x08\x12\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\x04\x1b\n\x0c\n\x05\
    \x04\0\x02\0\x05\x12\x03\x05\x04\n\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\
    \x05\x0b\x16\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\x19\x1a\n\x0b\n\x04\
    \x04\0\x02\x01\x12\x03\x06\x04&\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\
    \x06\x04\n\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x06\x0b!\n\x0c\n\x05\
    \x04\0\x02\x01\x03\x12\x03\x06$%\n\n\n\x02\x04\x01\x12\x04\t\0\x0e\x01\n\
    \n\n\x03\x04\x01\x01\x12\x03\t\x08\x11\n\x0b\n\x04\x04\x01\x02\0\x12\x03\
    \n\x04\x18\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\n\x04\n\n\x0c\n\x05\x04\
    \x01\x02\0\x01\x12\x03\n\x0b\x13\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\n\
    \x16\x17\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\x0b\x04\x1a\n\x0c\n\x05\x04\
    \x01\x02\x01\x05\x12\x03\x0b\x04\n\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\
    \x03\x0b\x0b\x15\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x0b\x18\x19\n\
    \x0b\n\x04\x04\x01\x02\x02\x12\x03\x0c\x04\x1c\n\x0c\n\x05\x04\x01\x02\
    \x02\x05\x12\x03\x0c\x04\n\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x0c\
    \x0b\x17\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x0c\x1a\x1b\n\x0b\n\x04\
    \x04\x01\x02\x03\x12\x03\r\x04'\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x03\
    \r\x04\n\n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03\r\x0b\"\n\x0c\n\x05\x04\
    \x01\x02\x03\x03\x12\x03\r%&\n\n\n\x02\x04\x02\x12\x04\x10\0\x15\x01\n\n\
    \n\x03\x04\x02\x01\x12\x03\x10\x08\x12\n\x0b\n\x04\x04\x02\x02\0\x12\x03\
    \x11\x04\x18\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\x11\x04\n\n\x0c\n\x05\
    \x04\x02\x02\0\x01\x12\x03\x11\x0b\x13\n\x0c\n\x05\x04\x02\x02\0\x03\x12\
    \x03\x11\x16\x17\n\x0b\n\x04\x04\x02\x02\x01\x12\x03\x12\x04\x19\n\x0c\n\
    \x05\x04\x02\x02\x01\x05\x12\x03\x12\x04\n\n\x0c\n\x05\x04\x02\x02\x01\
    \x01\x12\x03\x12\x0b\x14\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03\x12\x17\
    \x18\n\x0b\n\x04\x04\x02\x02\x02\x12\x03\x13\x04\x1b\n\x0c\n\x05\x04\x02\
    \x02\x02\x05\x12\x03\x13\x04\n\n\x0c\n\x05\x04\x02\x02\x02\x01\x12\x03\
    \x13\x0b\x16\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03\x13\x19\x1a\n\x0b\n\
    \x04\x04\x02\x02\x03\x12\x03\x14\x04\x1f\n\x0c\n\x05\x04\x02\x02\x03\x06\
    \x12\x03\x14\x04\x0e\n\x0c\n\x05\x04\x02\x02\x03\x01\x12\x03\x14\x0f\x1a\
    \n\x0c\n\x05\x04\x02\x02\x03\x03\x12\x03\x14\x1d\x1e\n\n\n\x02\x05\0\x12\
    \x04\x17\0\x1e\x01\n\n\n\x03\x05\0\x01\x12\x03\x17\x05\x0f\n\x0b\n\x04\
    \x05\0\x02\0\x12\x03\x18\x04\x1b\n\x0c\n\x05\x05\0\x02\0\x01\x12\x03\x18\
    \x04\x16\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\x18\x19\x1a\n\x0b\n\x04\x05\
    \0\x02\x01\x12\x03\x19\x04\x1a\n\x0c\n\x05\x05\0\x02\x01\x01\x12\x03\x19\
    \x04\x15\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x19\x18\x19\n\x0b\n\x04\
    \x05\0\x02\x02\x12\x03\x1a\x04\x1a\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x03\
    \x1a\x04\x15\n\x0c\n\x05\x05\0\x02\x02\x02\x12\x03\x1a\x18\x19\n\x0b\n\
    \x04\x05\0\x02\x03\x12\x03\x1b\x04\x1a\n\x0c\n\x05\x05\0\x02\x03\x01\x12\
    \x03\x1b\x04\x15\n\x0c\n\x05\x05\0\x02\x03\x02\x12\x03\x1b\x18\x19\n\x0b\
    \n\x04\x05\0\x02\x04\x12\x03\x1c\x04\x19\n\x0c\n\x05\x05\0\x02\x04\x01\
    \x12\x03\x1c\x04\x14\n\x0c\n\x05\x05\0\x02\x04\x02\x12\x03\x1c\x17\x18\n\
    \x0b\n\x04\x05\0\x02\x05\x12\x03\x1d\x04\x1a\n\x0c\n\x05\x05\0\x02\x05\
    \x01\x12\x03\x1d\x04\x15\n\x0c\n\x05\x05\0\x02\x05\x02\x12\x03\x1d\x18\
    \x19b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(SchemaMeta::generated_message_descriptor_data());
            messages.push(TableMeta::generated_message_descriptor_data());
            messages.push(ColumnMeta::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(ColumnType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
