// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `query.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

///  列过滤器 - 单个列的多个条件，逻辑关系：OR (同一个列的多个条件是 OR 关系
// @@protoc_insertion_point(message:laoflchdb.ColumnFilter)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ColumnFilter {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.ColumnFilter.column_name)
    pub column_name: ::std::string::String,
    // @@protoc_insertion_point(field:laoflchdb.ColumnFilter.conditions)
    pub conditions: ::std::vec::Vec<ColumnFilterCondition>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.ColumnFilter.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ColumnFilter {
    fn default() -> &'a ColumnFilter {
        <ColumnFilter as ::protobuf::Message>::default_instance()
    }
}

impl ColumnFilter {
    pub fn new() -> ColumnFilter {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "column_name",
            |m: &ColumnFilter| { &m.column_name },
            |m: &mut ColumnFilter| { &mut m.column_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "conditions",
            |m: &ColumnFilter| { &m.conditions },
            |m: &mut ColumnFilter| { &mut m.conditions },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ColumnFilter>(
            "ColumnFilter",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ColumnFilter {
    const NAME: &'static str = "ColumnFilter";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.column_name = is.read_string()?;
                },
                18 => {
                    self.conditions.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.column_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.column_name);
        }
        for value in &self.conditions {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.column_name.is_empty() {
            os.write_string(1, &self.column_name)?;
        }
        for v in &self.conditions {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ColumnFilter {
        ColumnFilter::new()
    }

    fn clear(&mut self) {
        self.column_name.clear();
        self.conditions.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ColumnFilter {
        static instance: ColumnFilter = ColumnFilter {
            column_name: ::std::string::String::new(),
            conditions: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ColumnFilter {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ColumnFilter").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ColumnFilter {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ColumnFilter {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  单个列过滤条件
// @@protoc_insertion_point(message:laoflchdb.ColumnFilterCondition)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ColumnFilterCondition {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.ColumnFilterCondition.op)
    pub op: ::protobuf::EnumOrUnknown<FilterOperator>,
    // @@protoc_insertion_point(field:laoflchdb.ColumnFilterCondition.value)
    pub value: ::protobuf::MessageField<super::field::Field>,
    // @@protoc_insertion_point(field:laoflchdb.ColumnFilterCondition.values)
    pub values: ::std::vec::Vec<super::field::Field>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.ColumnFilterCondition.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ColumnFilterCondition {
    fn default() -> &'a ColumnFilterCondition {
        <ColumnFilterCondition as ::protobuf::Message>::default_instance()
    }
}

impl ColumnFilterCondition {
    pub fn new() -> ColumnFilterCondition {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "op",
            |m: &ColumnFilterCondition| { &m.op },
            |m: &mut ColumnFilterCondition| { &mut m.op },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::field::Field>(
            "value",
            |m: &ColumnFilterCondition| { &m.value },
            |m: &mut ColumnFilterCondition| { &mut m.value },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "values",
            |m: &ColumnFilterCondition| { &m.values },
            |m: &mut ColumnFilterCondition| { &mut m.values },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ColumnFilterCondition>(
            "ColumnFilterCondition",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ColumnFilterCondition {
    const NAME: &'static str = "ColumnFilterCondition";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.op = is.read_enum_or_unknown()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.value)?;
                },
                26 => {
                    self.values.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.op != ::protobuf::EnumOrUnknown::new(FilterOperator::FILTER_OPERATOR_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.op.value());
        }
        if let Some(v) = self.value.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.values {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.op != ::protobuf::EnumOrUnknown::new(FilterOperator::FILTER_OPERATOR_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.op))?;
        }
        if let Some(v) = self.value.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        for v in &self.values {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ColumnFilterCondition {
        ColumnFilterCondition::new()
    }

    fn clear(&mut self) {
        self.op = ::protobuf::EnumOrUnknown::new(FilterOperator::FILTER_OPERATOR_UNSPECIFIED);
        self.value.clear();
        self.values.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ColumnFilterCondition {
        static instance: ColumnFilterCondition = ColumnFilterCondition {
            op: ::protobuf::EnumOrUnknown::from_i32(0),
            value: ::protobuf::MessageField::none(),
            values: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ColumnFilterCondition {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ColumnFilterCondition").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ColumnFilterCondition {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ColumnFilterCondition {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  表过滤器 - 单个表的多个列过滤器，逻辑关系：AND (CNF 中的一个 clause
// @@protoc_insertion_point(message:laoflchdb.TableFilter)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TableFilter {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.TableFilter.table_name)
    pub table_name: ::std::string::String,
    // @@protoc_insertion_point(field:laoflchdb.TableFilter.column_filters)
    pub column_filters: ::std::vec::Vec<ColumnFilter>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.TableFilter.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TableFilter {
    fn default() -> &'a TableFilter {
        <TableFilter as ::protobuf::Message>::default_instance()
    }
}

impl TableFilter {
    pub fn new() -> TableFilter {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "table_name",
            |m: &TableFilter| { &m.table_name },
            |m: &mut TableFilter| { &mut m.table_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "column_filters",
            |m: &TableFilter| { &m.column_filters },
            |m: &mut TableFilter| { &mut m.column_filters },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TableFilter>(
            "TableFilter",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TableFilter {
    const NAME: &'static str = "TableFilter";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.table_name = is.read_string()?;
                },
                18 => {
                    self.column_filters.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.table_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.table_name);
        }
        for value in &self.column_filters {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.table_name.is_empty() {
            os.write_string(1, &self.table_name)?;
        }
        for v in &self.column_filters {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TableFilter {
        TableFilter::new()
    }

    fn clear(&mut self) {
        self.table_name.clear();
        self.column_filters.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TableFilter {
        static instance: TableFilter = TableFilter {
            table_name: ::std::string::String::new(),
            column_filters: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TableFilter {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TableFilter").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TableFilter {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TableFilter {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  查询请求 - 完整的 CNF 表达式：(表1 AND 列1) AND (表2 AND 列2) ...
// @@protoc_insertion_point(message:laoflchdb.Query)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Query {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.Query.table_filters)
    pub table_filters: ::std::vec::Vec<TableFilter>,
    // @@protoc_insertion_point(field:laoflchdb.Query.limit)
    pub limit: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:laoflchdb.Query.offset)
    pub offset: ::std::option::Option<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.Query.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Query {
    fn default() -> &'a Query {
        <Query as ::protobuf::Message>::default_instance()
    }
}

impl Query {
    pub fn new() -> Query {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "table_filters",
            |m: &Query| { &m.table_filters },
            |m: &mut Query| { &mut m.table_filters },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "limit",
            |m: &Query| { &m.limit },
            |m: &mut Query| { &mut m.limit },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "offset",
            |m: &Query| { &m.offset },
            |m: &mut Query| { &mut m.offset },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Query>(
            "Query",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Query {
    const NAME: &'static str = "Query";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.table_filters.push(is.read_message()?);
                },
                16 => {
                    self.limit = ::std::option::Option::Some(is.read_uint32()?);
                },
                24 => {
                    self.offset = ::std::option::Option::Some(is.read_uint32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.table_filters {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.limit {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        if let Some(v) = self.offset {
            my_size += ::protobuf::rt::uint32_size(3, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.table_filters {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if let Some(v) = self.limit {
            os.write_uint32(2, v)?;
        }
        if let Some(v) = self.offset {
            os.write_uint32(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Query {
        Query::new()
    }

    fn clear(&mut self) {
        self.table_filters.clear();
        self.limit = ::std::option::Option::None;
        self.offset = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Query {
        static instance: Query = Query {
            table_filters: ::std::vec::Vec::new(),
            limit: ::std::option::Option::None,
            offset: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Query {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Query").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Query {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Query {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  查询结果
// @@protoc_insertion_point(message:laoflchdb.QueryResult)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct QueryResult {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.QueryResult.rows)
    pub rows: ::std::vec::Vec<QueryRow>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.QueryResult.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a QueryResult {
    fn default() -> &'a QueryResult {
        <QueryResult as ::protobuf::Message>::default_instance()
    }
}

impl QueryResult {
    pub fn new() -> QueryResult {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "rows",
            |m: &QueryResult| { &m.rows },
            |m: &mut QueryResult| { &mut m.rows },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<QueryResult>(
            "QueryResult",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for QueryResult {
    const NAME: &'static str = "QueryResult";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.rows.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.rows {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.rows {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> QueryResult {
        QueryResult::new()
    }

    fn clear(&mut self) {
        self.rows.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static QueryResult {
        static instance: QueryResult = QueryResult {
            rows: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for QueryResult {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("QueryResult").unwrap()).clone()
    }
}

impl ::std::fmt::Display for QueryResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for QueryResult {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  查询返回的行（包含表名和行数据）
// @@protoc_insertion_point(message:laoflchdb.QueryRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct QueryRow {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.QueryRow.table_name)
    pub table_name: ::std::string::String,
    // @@protoc_insertion_point(field:laoflchdb.QueryRow.row_id)
    pub row_id: u64,
    // @@protoc_insertion_point(field:laoflchdb.QueryRow.row)
    pub row: ::protobuf::MessageField<super::row::Row>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.QueryRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a QueryRow {
    fn default() -> &'a QueryRow {
        <QueryRow as ::protobuf::Message>::default_instance()
    }
}

impl QueryRow {
    pub fn new() -> QueryRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "table_name",
            |m: &QueryRow| { &m.table_name },
            |m: &mut QueryRow| { &mut m.table_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "row_id",
            |m: &QueryRow| { &m.row_id },
            |m: &mut QueryRow| { &mut m.row_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::row::Row>(
            "row",
            |m: &QueryRow| { &m.row },
            |m: &mut QueryRow| { &mut m.row },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<QueryRow>(
            "QueryRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for QueryRow {
    const NAME: &'static str = "QueryRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.table_name = is.read_string()?;
                },
                16 => {
                    self.row_id = is.read_uint64()?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.row)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.table_name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.table_name);
        }
        if self.row_id != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.row_id);
        }
        if let Some(v) = self.row.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.table_name.is_empty() {
            os.write_string(1, &self.table_name)?;
        }
        if self.row_id != 0 {
            os.write_uint64(2, self.row_id)?;
        }
        if let Some(v) = self.row.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> QueryRow {
        QueryRow::new()
    }

    fn clear(&mut self) {
        self.table_name.clear();
        self.row_id = 0;
        self.row.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static QueryRow {
        static instance: QueryRow = QueryRow {
            table_name: ::std::string::String::new(),
            row_id: 0,
            row: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for QueryRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("QueryRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for QueryRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for QueryRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  过滤操作符
#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:laoflchdb.FilterOperator)
pub enum FilterOperator {
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_UNSPECIFIED)
    FILTER_OPERATOR_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_EQ)
    FILTER_OPERATOR_EQ = 1,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_NEQ)
    FILTER_OPERATOR_NEQ = 2,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_GT)
    FILTER_OPERATOR_GT = 3,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_GTE)
    FILTER_OPERATOR_GTE = 4,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_LT)
    FILTER_OPERATOR_LT = 5,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_LTE)
    FILTER_OPERATOR_LTE = 6,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_IN)
    FILTER_OPERATOR_IN = 7,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_NOT_IN)
    FILTER_OPERATOR_NOT_IN = 8,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_LIKE)
    FILTER_OPERATOR_LIKE = 9,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_IS_NULL)
    FILTER_OPERATOR_IS_NULL = 10,
    // @@protoc_insertion_point(enum_value:laoflchdb.FilterOperator.FILTER_OPERATOR_IS_NOT_NULL)
    FILTER_OPERATOR_IS_NOT_NULL = 11,
}

impl ::protobuf::Enum for FilterOperator {
    const NAME: &'static str = "FilterOperator";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FilterOperator> {
        match value {
            0 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_UNSPECIFIED),
            1 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_EQ),
            2 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_NEQ),
            3 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_GT),
            4 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_GTE),
            5 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_LT),
            6 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_LTE),
            7 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_IN),
            8 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_NOT_IN),
            9 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_LIKE),
            10 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_IS_NULL),
            11 => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_IS_NOT_NULL),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<FilterOperator> {
        match str {
            "FILTER_OPERATOR_UNSPECIFIED" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_UNSPECIFIED),
            "FILTER_OPERATOR_EQ" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_EQ),
            "FILTER_OPERATOR_NEQ" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_NEQ),
            "FILTER_OPERATOR_GT" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_GT),
            "FILTER_OPERATOR_GTE" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_GTE),
            "FILTER_OPERATOR_LT" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_LT),
            "FILTER_OPERATOR_LTE" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_LTE),
            "FILTER_OPERATOR_IN" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_IN),
            "FILTER_OPERATOR_NOT_IN" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_NOT_IN),
            "FILTER_OPERATOR_LIKE" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_LIKE),
            "FILTER_OPERATOR_IS_NULL" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_IS_NULL),
            "FILTER_OPERATOR_IS_NOT_NULL" => ::std::option::Option::Some(FilterOperator::FILTER_OPERATOR_IS_NOT_NULL),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [FilterOperator] = &[
        FilterOperator::FILTER_OPERATOR_UNSPECIFIED,
        FilterOperator::FILTER_OPERATOR_EQ,
        FilterOperator::FILTER_OPERATOR_NEQ,
        FilterOperator::FILTER_OPERATOR_GT,
        FilterOperator::FILTER_OPERATOR_GTE,
        FilterOperator::FILTER_OPERATOR_LT,
        FilterOperator::FILTER_OPERATOR_LTE,
        FilterOperator::FILTER_OPERATOR_IN,
        FilterOperator::FILTER_OPERATOR_NOT_IN,
        FilterOperator::FILTER_OPERATOR_LIKE,
        FilterOperator::FILTER_OPERATOR_IS_NULL,
        FilterOperator::FILTER_OPERATOR_IS_NOT_NULL,
    ];
}

impl ::protobuf::EnumFull for FilterOperator {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("FilterOperator").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for FilterOperator {
    fn default() -> Self {
        FilterOperator::FILTER_OPERATOR_UNSPECIFIED
    }
}

impl FilterOperator {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<FilterOperator>("FilterOperator")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bquery.proto\x12\tlaoflchdb\x1a\x0bfield.proto\x1a\trow.proto\"q\n\
    \x0cColumnFilter\x12\x1f\n\x0bcolumn_name\x18\x01\x20\x01(\tR\ncolumnNam\
    e\x12@\n\nconditions\x18\x02\x20\x03(\x0b2\x20.laoflchdb.ColumnFilterCon\
    ditionR\nconditions\"\x94\x01\n\x15ColumnFilterCondition\x12)\n\x02op\
    \x18\x01\x20\x01(\x0e2\x19.laoflchdb.FilterOperatorR\x02op\x12&\n\x05val\
    ue\x18\x02\x20\x01(\x0b2\x10.laoflchdb.FieldR\x05value\x12(\n\x06values\
    \x18\x03\x20\x03(\x0b2\x10.laoflchdb.FieldR\x06values\"l\n\x0bTableFilte\
    r\x12\x1d\n\ntable_name\x18\x01\x20\x01(\tR\ttableName\x12>\n\x0ecolumn_\
    filters\x18\x02\x20\x03(\x0b2\x17.laoflchdb.ColumnFilterR\rcolumnFilters\
    \"\x91\x01\n\x05Query\x12;\n\rtable_filters\x18\x01\x20\x03(\x0b2\x16.la\
    oflchdb.TableFilterR\x0ctableFilters\x12\x19\n\x05limit\x18\x02\x20\x01(\
    \rH\0R\x05limit\x88\x01\x01\x12\x1b\n\x06offset\x18\x03\x20\x01(\rH\x01R\
    \x06offset\x88\x01\x01B\x08\n\x06_limitB\t\n\x07_offset\"6\n\x0bQueryRes\
    ult\x12'\n\x04rows\x18\x01\x20\x03(\x0b2\x13.laoflchdb.QueryRowR\x04rows\
    \"b\n\x08QueryRow\x12\x1d\n\ntable_name\x18\x01\x20\x01(\tR\ttableName\
    \x12\x15\n\x06row_id\x18\x02\x20\x01(\x04R\x05rowId\x12\x20\n\x03row\x18\
    \x03\x20\x01(\x0b2\x0e.laoflchdb.RowR\x03row*\xd0\x02\n\x0eFilterOperato\
    r\x12\x1f\n\x1bFILTER_OPERATOR_UNSPECIFIED\x10\0\x12\x16\n\x12FILTER_OPE\
    RATOR_EQ\x10\x01\x12\x17\n\x13FILTER_OPERATOR_NEQ\x10\x02\x12\x16\n\x12F\
    ILTER_OPERATOR_GT\x10\x03\x12\x17\n\x13FILTER_OPERATOR_GTE\x10\x04\x12\
    \x16\n\x12FILTER_OPERATOR_LT\x10\x05\x12\x17\n\x13FILTER_OPERATOR_LTE\
    \x10\x06\x12\x16\n\x12FILTER_OPERATOR_IN\x10\x07\x12\x1a\n\x16FILTER_OPE\
    RATOR_NOT_IN\x10\x08\x12\x18\n\x14FILTER_OPERATOR_LIKE\x10\t\x12\x1b\n\
    \x17FILTER_OPERATOR_IS_NULL\x10\n\x12\x1f\n\x1bFILTER_OPERATOR_IS_NOT_NU\
    LL\x10\x0bJ\xf8\x12\n\x06\x12\x04\0\0;\x01\n\x08\n\x01\x0c\x12\x03\0\0\
    \x12\n\x08\n\x01\x02\x12\x03\x02\0\x12\n\t\n\x02\x03\0\x12\x03\x04\0\x15\
    \n\t\n\x02\x03\x01\x12\x03\x05\0\x13\n\x1d\n\x02\x05\0\x12\x04\x08\0\x15\
    \x01\x1a\x11\x20\xe8\xbf\x87\xe6\xbb\xa4\xe6\x93\x8d\xe4\xbd\x9c\xe7\xac\
    \xa6\n\n\n\n\x03\x05\0\x01\x12\x03\x08\x05\x13\n\x0b\n\x04\x05\0\x02\0\
    \x12\x03\t\x04$\n\x0c\n\x05\x05\0\x02\0\x01\x12\x03\t\x04\x1f\n\x0c\n\
    \x05\x05\0\x02\0\x02\x12\x03\t\"#\n\x15\n\x04\x05\0\x02\x01\x12\x03\n\
    \x04\x1b\"\x08\x20\xe7\xad\x89\xe4\xba\x8e\n\n\x0c\n\x05\x05\0\x02\x01\
    \x01\x12\x03\n\x04\x16\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\n\x19\x1a\n\
    \x18\n\x04\x05\0\x02\x02\x12\x03\x0b\x04\x1c\"\x0b\x20\xe4\xb8\x8d\xe7\
    \xad\x89\xe4\xba\x8e\n\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x03\x0b\x04\x17\
    \n\x0c\n\x05\x05\0\x02\x02\x02\x12\x03\x0b\x1a\x1b\n\x15\n\x04\x05\0\x02\
    \x03\x12\x03\x0c\x04\x1b\"\x08\x20\xe5\xa4\xa7\xe4\xba\x8e\n\n\x0c\n\x05\
    \x05\0\x02\x03\x01\x12\x03\x0c\x04\x16\n\x0c\n\x05\x05\0\x02\x03\x02\x12\
    \x03\x0c\x19\x1a\n\x1b\n\x04\x05\0\x02\x04\x12\x03\r\x04\x1c\"\x0e\x20\
    \xe5\xa4\xa7\xe4\xba\x8e\xe7\xad\x89\xe4\xba\x8e\n\n\x0c\n\x05\x05\0\x02\
    \x04\x01\x12\x03\r\x04\x17\n\x0c\n\x05\x05\0\x02\x04\x02\x12\x03\r\x1a\
    \x1b\n\x15\n\x04\x05\0\x02\x05\x12\x03\x0e\x04\x1b\"\x08\x20\xe5\xb0\x8f\
    \xe4\xba\x8e\n\n\x0c\n\x05\x05\0\x02\x05\x01\x12\x03\x0e\x04\x16\n\x0c\n\
    \x05\x05\0\x02\x05\x02\x12\x03\x0e\x19\x1a\n\x1b\n\x04\x05\0\x02\x06\x12\
    \x03\x0f\x04\x1c\"\x0e\x20\xe5\xb0\x8f\xe4\xba\x8e\xe7\xad\x89\xe4\xba\
    \x8e\n\n\x0c\n\x05\x05\0\x02\x06\x01\x12\x03\x0f\x04\x17\n\x0c\n\x05\x05\
    \0\x02\x06\x02\x12\x03\x0f\x1a\x1b\n\x1b\n\x04\x05\0\x02\x07\x12\x03\x10\
    \x04\x1b\"\x0e\x20\xe5\x9c\xa8\xe5\x88\x97\xe8\xa1\xa8\xe4\xb8\xad\n\n\
    \x0c\n\x05\x05\0\x02\x07\x01\x12\x03\x10\x04\x16\n\x0c\n\x05\x05\0\x02\
    \x07\x02\x12\x03\x10\x19\x1a\n\x1e\n\x04\x05\0\x02\x08\x12\x03\x11\x04\
    \x1f\"\x11\x20\xe4\xb8\x8d\xe5\x9c\xa8\xe5\x88\x97\xe8\xa1\xa8\xe4\xb8\
    \xad\n\n\x0c\n\x05\x05\0\x02\x08\x01\x12\x03\x11\x04\x1a\n\x0c\n\x05\x05\
    \0\x02\x08\x02\x12\x03\x11\x1d\x1e\n\x1e\n\x04\x05\0\x02\t\x12\x03\x12\
    \x04\x1d\"\x11\x20\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe5\x8c\xb9\xe9\
    \x85\x8d\n\n\x0c\n\x05\x05\0\x02\t\x01\x12\x03\x12\x04\x18\n\x0c\n\x05\
    \x05\0\x02\t\x02\x12\x03\x12\x1b\x1c\n\x15\n\x04\x05\0\x02\n\x12\x03\x13\
    \x04!\"\x08\x20\xe4\xb8\xba\xe7\xa9\xba\n\n\x0c\n\x05\x05\0\x02\n\x01\
    \x12\x03\x13\x04\x1b\n\x0c\n\x05\x05\0\x02\n\x02\x12\x03\x13\x1e\x20\n\
    \x18\n\x04\x05\0\x02\x0b\x12\x03\x14\x04%\"\x0b\x20\xe4\xb8\x8d\xe4\xb8\
    \xba\xe7\xa9\xba\n\n\x0c\n\x05\x05\0\x02\x0b\x01\x12\x03\x14\x04\x1f\n\
    \x0c\n\x05\x05\0\x02\x0b\x02\x12\x03\x14\"$\ns\n\x02\x04\0\x12\x04\x18\0\
    \x1b\x01\x1ag\x20\xe5\x88\x97\xe8\xbf\x87\xe6\xbb\xa4\xe5\x99\xa8\x20-\
    \x20\xe5\x8d\x95\xe4\xb8\xaa\xe5\x88\x97\xe7\x9a\x84\xe5\xa4\x9a\xe4\xb8\
    \xaa\xe6\x9d\xa1\xe4\xbb\xb6\xef\xbc\x8c\xe9\x80\xbb\xe8\xbe\x91\xe5\x85\
    \xb3\xe7\xb3\xbb\xef\xbc\x9aOR\x20(\xe5\x90\x8c\xe4\xb8\x80\xe4\xb8\xaa\
    \xe5\x88\x97\xe7\x9a\x84\xe5\xa4\x9a\xe4\xb8\xaa\xe6\x9d\xa1\xe4\xbb\xb6\
    \xe6\x98\xaf\x20OR\x20\xe5\x85\xb3\xe7\xb3\xbb\n\n\n\n\x03\x04\0\x01\x12\
    \x03\x18\x08\x14\n\x15\n\x04\x04\0\x02\0\x12\x03\x19\x04\x1b\"\x08\x20\
    \xe5\x88\x97\xe5\x90\x8d\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x19\x04\n\
    \n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x19\x0b\x16\n\x0c\n\x05\x04\0\x02\0\
    \x03\x12\x03\x19\x19\x1a\n'\n\x04\x04\0\x02\x01\x12\x03\x1a\x042\"\x1a\
    \x20\xe5\xa4\x9a\xe4\xb8\xaa\xe6\x9d\xa1\xe4\xbb\xb6\xef\xbc\x8cOR\x20\
    \xe5\x85\xb3\xe7\xb3\xbb\n\n\x0c\n\x05\x04\0\x02\x01\x04\x12\x03\x1a\x04\
    \x0c\n\x0c\n\x05\x04\0\x02\x01\x06\x12\x03\x1a\r\"\n\x0c\n\x05\x04\0\x02\
    \x01\x01\x12\x03\x1a#-\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x1a01\n#\n\
    \x02\x04\x01\x12\x04\x1e\0\"\x01\x1a\x17\x20\xe5\x8d\x95\xe4\xb8\xaa\xe5\
    \x88\x97\xe8\xbf\x87\xe6\xbb\xa4\xe6\x9d\xa1\xe4\xbb\xb6\n\n\n\n\x03\x04\
    \x01\x01\x12\x03\x1e\x08\x1d\n\x18\n\x04\x04\x01\x02\0\x12\x03\x1f\x04\
    \x1a\"\x0b\x20\xe6\x93\x8d\xe4\xbd\x9c\xe7\xac\xa6\n\n\x0c\n\x05\x04\x01\
    \x02\0\x06\x12\x03\x1f\x04\x12\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x1f\
    \x13\x15\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x1f\x18\x19\nA\n\x04\x04\
    \x01\x02\x01\x12\x03\x20\x04\x14\"4\x20\xe6\xaf\x94\xe8\xbe\x83\xe5\x80\
    \xbc\xef\xbc\x88\xe9\x99\xa4\xe4\xba\x86\x20IN/NOT_IN\x20\xe6\x93\x8d\
    \xe4\xbd\x9c\xe7\xac\xa6\xe5\xa4\x96\xe4\xbd\xbf\xe7\x94\xa8\xef\xbc\x89\
    \n\n\x0c\n\x05\x04\x01\x02\x01\x06\x12\x03\x20\x04\t\n\x0c\n\x05\x04\x01\
    \x02\x01\x01\x12\x03\x20\n\x0f\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\
    \x20\x12\x13\n.\n\x04\x04\x01\x02\x02\x12\x03!\x04\x1e\"!\x20\xe5\xa4\
    \x9a\xe4\xb8\xaa\xe5\x80\xbc\xef\xbc\x88\xe7\x94\xa8\xe4\xba\x8e\x20IN/N\
    OT_IN\xef\xbc\x89\n\n\x0c\n\x05\x04\x01\x02\x02\x04\x12\x03!\x04\x0c\n\
    \x0c\n\x05\x04\x01\x02\x02\x06\x12\x03!\r\x12\n\x0c\n\x05\x04\x01\x02\
    \x02\x01\x12\x03!\x13\x19\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03!\x1c\
    \x1d\ni\n\x02\x04\x02\x12\x04%\0(\x01\x1a]\x20\xe8\xa1\xa8\xe8\xbf\x87\
    \xe6\xbb\xa4\xe5\x99\xa8\x20-\x20\xe5\x8d\x95\xe4\xb8\xaa\xe8\xa1\xa8\
    \xe7\x9a\x84\xe5\xa4\x9a\xe4\xb8\xaa\xe5\x88\x97\xe8\xbf\x87\xe6\xbb\xa4\
    \xe5\x99\xa8\xef\xbc\x8c\xe9\x80\xbb\xe8\xbe\x91\xe5\x85\xb3\xe7\xb3\xbb\
    \xef\xbc\x9aAND\x20(CNF\x20\xe4\xb8\xad\xe7\x9a\x84\xe4\xb8\x80\xe4\xb8\
    \xaa\x20clause\n\n\n\n\x03\x04\x02\x01\x12\x03%\x08\x13\n\x15\n\x04\x04\
    \x02\x02\0\x12\x03&\x04\x1a\"\x08\x20\xe8\xa1\xa8\xe5\x90\x8d\n\n\x0c\n\
    \x05\x04\x02\x02\0\x05\x12\x03&\x04\n\n\x0c\n\x05\x04\x02\x02\0\x01\x12\
    \x03&\x0b\x15\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03&\x18\x19\n.\n\x04\
    \x04\x02\x02\x01\x12\x03'\x04-\"!\x20\xe5\xa4\x9a\xe4\xb8\xaa\xe5\x88\
    \x97\xe8\xbf\x87\xe6\xbb\xa4\xe5\x99\xa8\xef\xbc\x8cAND\x20\xe5\x85\xb3\
    \xe7\xb3\xbb\n\n\x0c\n\x05\x04\x02\x02\x01\x04\x12\x03'\x04\x0c\n\x0c\n\
    \x05\x04\x02\x02\x01\x06\x12\x03'\r\x19\n\x0c\n\x05\x04\x02\x02\x01\x01\
    \x12\x03'\x1a(\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03'+,\n^\n\x02\x04\
    \x03\x12\x04+\0/\x01\x1aR\x20\xe6\x9f\xa5\xe8\xaf\xa2\xe8\xaf\xb7\xe6\
    \xb1\x82\x20-\x20\xe5\xae\x8c\xe6\x95\xb4\xe7\x9a\x84\x20CNF\x20\xe8\xa1\
    \xa8\xe8\xbe\xbe\xe5\xbc\x8f\xef\xbc\x9a(\xe8\xa1\xa81\x20AND\x20\xe5\
    \x88\x971)\x20AND\x20(\xe8\xa1\xa82\x20AND\x20\xe5\x88\x972)\x20...\n\n\
    \n\n\x03\x04\x03\x01\x12\x03+\x08\r\n4\n\x04\x04\x03\x02\0\x12\x03,\x04+\
    \"'\x20\xe5\xa4\x9a\xe4\xb8\xaa\xe8\xa1\xa8\xe8\xbf\x87\xe6\xbb\xa4\xe5\
    \x99\xa8\xef\xbc\x8cAND\x20\xe5\x85\xb3\xe7\xb3\xbb\x20(CNF)\n\n\x0c\n\
    \x05\x04\x03\x02\0\x04\x12\x03,\x04\x0c\n\x0c\n\x05\x04\x03\x02\0\x06\
    \x12\x03,\r\x18\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03,\x19&\n\x0c\n\x05\
    \x04\x03\x02\0\x03\x12\x03,)*\n'\n\x04\x04\x03\x02\x01\x12\x03-\x04\x1e\
    \"\x1a\x20\xe8\xbf\x94\xe5\x9b\x9e\xe7\xbb\x93\xe6\x9e\x9c\xe6\x95\xb0\
    \xe9\x87\x8f\xe9\x99\x90\xe5\x88\xb6\n\n\x0c\n\x05\x04\x03\x02\x01\x04\
    \x12\x03-\x04\x0c\n\x0c\n\x05\x04\x03\x02\x01\x05\x12\x03-\r\x13\n\x0c\n\
    \x05\x04\x03\x02\x01\x01\x12\x03-\x14\x19\n\x0c\n\x05\x04\x03\x02\x01\
    \x03\x12\x03-\x1c\x1d\n$\n\x04\x04\x03\x02\x02\x12\x03.\x04\x1f\"\x17\
    \x20\xe8\xb7\xb3\xe8\xbf\x87\xe7\x9a\x84\xe7\xbb\x93\xe6\x9e\x9c\xe6\x95\
    \xb0\xe9\x87\x8f\n\n\x0c\n\x05\x04\x03\x02\x02\x04\x12\x03.\x04\x0c\n\
    \x0c\n\x05\x04\x03\x02\x02\x05\x12\x03.\r\x13\n\x0c\n\x05\x04\x03\x02\
    \x02\x01\x12\x03.\x14\x1a\n\x0c\n\x05\x04\x03\x02\x02\x03\x12\x03.\x1d\
    \x1e\n\x1a\n\x02\x04\x04\x12\x042\04\x01\x1a\x0e\x20\xe6\x9f\xa5\xe8\xaf\
    \xa2\xe7\xbb\x93\xe6\x9e\x9c\n\n\n\n\x03\x04\x04\x01\x12\x032\x08\x13\n\
    \x1e\n\x04\x04\x04\x02\0\x12\x033\x04\x1f\"\x11\x20\xe6\x9f\xa5\xe8\xaf\
    \xa2\xe5\x88\xb0\xe7\x9a\x84\xe8\xa1\x8c\n\n\x0c\n\x05\x04\x04\x02\0\x04\
    \x12\x033\x04\x0c\n\x0c\n\x05\x04\x04\x02\0\x06\x12\x033\r\x15\n\x0c\n\
    \x05\x04\x04\x02\0\x01\x12\x033\x16\x1a\n\x0c\n\x05\x04\x04\x02\0\x03\
    \x12\x033\x1d\x1e\n>\n\x02\x04\x05\x12\x047\0;\x01\x1a2\x20\xe6\x9f\xa5\
    \xe8\xaf\xa2\xe8\xbf\x94\xe5\x9b\x9e\xe7\x9a\x84\xe8\xa1\x8c\xef\xbc\x88\
    \xe5\x8c\x85\xe5\x90\xab\xe8\xa1\xa8\xe5\x90\x8d\xe5\x92\x8c\xe8\xa1\x8c\
    \xe6\x95\xb0\xe6\x8d\xae\xef\xbc\x89\n\n\n\n\x03\x04\x05\x01\x12\x037\
    \x08\x10\n\x0b\n\x04\x04\x05\x02\0\x12\x038\x04\x1a\n\x0c\n\x05\x04\x05\
    \x02\0\x05\x12\x038\x04\n\n\x0c\n\x05\x04\x05\x02\0\x01\x12\x038\x0b\x15\
    \n\x0c\n\x05\x04\x05\x02\0\x03\x12\x038\x18\x19\n\x0b\n\x04\x04\x05\x02\
    \x01\x12\x039\x04\x16\n\x0c\n\x05\x04\x05\x02\x01\x05\x12\x039\x04\n\n\
    \x0c\n\x05\x04\x05\x02\x01\x01\x12\x039\x0b\x11\n\x0c\n\x05\x04\x05\x02\
    \x01\x03\x12\x039\x14\x15\n\x0b\n\x04\x04\x05\x02\x02\x12\x03:\x04\x10\n\
    \x0c\n\x05\x04\x05\x02\x02\x06\x12\x03:\x04\x07\n\x0c\n\x05\x04\x05\x02\
    \x02\x01\x12\x03:\x08\x0b\n\x0c\n\x05\x04\x05\x02\x02\x03\x12\x03:\x0e\
    \x0fb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::field::file_descriptor().clone());
            deps.push(super::row::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(6);
            messages.push(ColumnFilter::generated_message_descriptor_data());
            messages.push(ColumnFilterCondition::generated_message_descriptor_data());
            messages.push(TableFilter::generated_message_descriptor_data());
            messages.push(Query::generated_message_descriptor_data());
            messages.push(QueryResult::generated_message_descriptor_data());
            messages.push(QueryRow::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(FilterOperator::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
