// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `row.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:laoflchdb.Row)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Row {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.Row.row_type)
    pub row_type: ::protobuf::EnumOrUnknown<RowType>,
    // @@protoc_insertion_point(field:laoflchdb.Row.version)
    pub version: u32,
    // @@protoc_insertion_point(field:laoflchdb.Row.data)
    pub data: ::std::vec::Vec<::std::vec::Vec<u8>>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.Row.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Row {
    fn default() -> &'a Row {
        <Row as ::protobuf::Message>::default_instance()
    }
}

impl Row {
    pub fn new() -> Row {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "row_type",
            |m: &Row| { &m.row_type },
            |m: &mut Row| { &mut m.row_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "version",
            |m: &Row| { &m.version },
            |m: &mut Row| { &mut m.version },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "data",
            |m: &Row| { &m.data },
            |m: &mut Row| { &mut m.data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Row>(
            "Row",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Row {
    const NAME: &'static str = "Row";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.row_type = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.version = is.read_uint32()?;
                },
                26 => {
                    self.data.push(is.read_bytes()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.row_type != ::protobuf::EnumOrUnknown::new(RowType::ROW_TYPE_NORMAL) {
            my_size += ::protobuf::rt::int32_size(1, self.row_type.value());
        }
        if self.version != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.version);
        }
        for value in &self.data {
            my_size += ::protobuf::rt::bytes_size(3, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.row_type != ::protobuf::EnumOrUnknown::new(RowType::ROW_TYPE_NORMAL) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.row_type))?;
        }
        if self.version != 0 {
            os.write_uint32(2, self.version)?;
        }
        for v in &self.data {
            os.write_bytes(3, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Row {
        Row::new()
    }

    fn clear(&mut self) {
        self.row_type = ::protobuf::EnumOrUnknown::new(RowType::ROW_TYPE_NORMAL);
        self.version = 0;
        self.data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Row {
        static instance: Row = Row {
            row_type: ::protobuf::EnumOrUnknown::from_i32(0),
            version: 0,
            data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Row {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Row").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Row {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Row {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:laoflchdb.RowType)
pub enum RowType {
    // @@protoc_insertion_point(enum_value:laoflchdb.RowType.ROW_TYPE_NORMAL)
    ROW_TYPE_NORMAL = 0,
    // @@protoc_insertion_point(enum_value:laoflchdb.RowType.ROW_TYPE_RAW)
    ROW_TYPE_RAW = 1,
}

impl ::protobuf::Enum for RowType {
    const NAME: &'static str = "RowType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<RowType> {
        match value {
            0 => ::std::option::Option::Some(RowType::ROW_TYPE_NORMAL),
            1 => ::std::option::Option::Some(RowType::ROW_TYPE_RAW),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<RowType> {
        match str {
            "ROW_TYPE_NORMAL" => ::std::option::Option::Some(RowType::ROW_TYPE_NORMAL),
            "ROW_TYPE_RAW" => ::std::option::Option::Some(RowType::ROW_TYPE_RAW),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [RowType] = &[
        RowType::ROW_TYPE_NORMAL,
        RowType::ROW_TYPE_RAW,
    ];
}

impl ::protobuf::EnumFull for RowType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("RowType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for RowType {
    fn default() -> Self {
        RowType::ROW_TYPE_NORMAL
    }
}

impl RowType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<RowType>("RowType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\trow.proto\x12\tlaoflchdb\"b\n\x03Row\x12-\n\x08row_type\x18\x01\x20\
    \x01(\x0e2\x12.laoflchdb.RowTypeR\x07rowType\x12\x18\n\x07version\x18\
    \x02\x20\x01(\rR\x07version\x12\x12\n\x04data\x18\x03\x20\x03(\x0cR\x04d\
    ata*0\n\x07RowType\x12\x13\n\x0fROW_TYPE_NORMAL\x10\0\x12\x10\n\x0cROW_T\
    YPE_RAW\x10\x01J\xd1\x02\n\x06\x12\x04\0\0\r\x01\n\x08\n\x01\x0c\x12\x03\
    \0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x12\n\n\n\x02\x05\0\x12\x04\x04\0\
    \x07\x01\n\n\n\x03\x05\0\x01\x12\x03\x04\x05\x0c\n\x0b\n\x04\x05\0\x02\0\
    \x12\x03\x05\x04\x18\n\x0c\n\x05\x05\0\x02\0\x01\x12\x03\x05\x04\x13\n\
    \x0c\n\x05\x05\0\x02\0\x02\x12\x03\x05\x16\x17\n\x0b\n\x04\x05\0\x02\x01\
    \x12\x03\x06\x04\x15\n\x0c\n\x05\x05\0\x02\x01\x01\x12\x03\x06\x04\x10\n\
    \x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x06\x13\x14\n\n\n\x02\x04\0\x12\x04\
    \t\0\r\x01\n\n\n\x03\x04\0\x01\x12\x03\t\x08\x0b\n\x0b\n\x04\x04\0\x02\0\
    \x12\x03\n\x04\x19\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\n\x04\x0b\n\x0c\n\
    \x05\x04\0\x02\0\x01\x12\x03\n\x0c\x14\n\x0c\n\x05\x04\0\x02\0\x03\x12\
    \x03\n\x17\x18\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x0b\x04\x17\n\x0c\n\x05\
    \x04\0\x02\x01\x05\x12\x03\x0b\x04\n\n\x0c\n\x05\x04\0\x02\x01\x01\x12\
    \x03\x0b\x0b\x12\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x0b\x15\x16\n\x0b\
    \n\x04\x04\0\x02\x02\x12\x03\x0c\x04\x1c\n\x0c\n\x05\x04\0\x02\x02\x04\
    \x12\x03\x0c\x04\x0c\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0c\r\x12\n\
    \x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x0c\x13\x17\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03\x0c\x1a\x1bb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Row::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(RowType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
