// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `field.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:laoflchdb.Field)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Field {
    // message oneof groups
    pub value: ::std::option::Option<field::Value>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.Field.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Field {
    fn default() -> &'a Field {
        <Field as ::protobuf::Message>::default_instance()
    }
}

impl Field {
    pub fn new() -> Field {
        ::std::default::Default::default()
    }

    // .laoflchdb.String string_value = 1;

    pub fn string_value(&self) -> &String {
        match self.value {
            ::std::option::Option::Some(field::Value::StringValue(ref v)) => v,
            _ => <String as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_string_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_string_value(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(field::Value::StringValue(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_string_value(&mut self, v: String) {
        self.value = ::std::option::Option::Some(field::Value::StringValue(v))
    }

    // Mutable pointer to the field.
    pub fn mut_string_value(&mut self) -> &mut String {
        if let ::std::option::Option::Some(field::Value::StringValue(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(field::Value::StringValue(String::new()));
        }
        match self.value {
            ::std::option::Option::Some(field::Value::StringValue(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_string_value(&mut self) -> String {
        if self.has_string_value() {
            match self.value.take() {
                ::std::option::Option::Some(field::Value::StringValue(v)) => v,
                _ => panic!(),
            }
        } else {
            String::new()
        }
    }

    // .laoflchdb.Integer integer_value = 2;

    pub fn integer_value(&self) -> &Integer {
        match self.value {
            ::std::option::Option::Some(field::Value::IntegerValue(ref v)) => v,
            _ => <Integer as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_integer_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_integer_value(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(field::Value::IntegerValue(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_integer_value(&mut self, v: Integer) {
        self.value = ::std::option::Option::Some(field::Value::IntegerValue(v))
    }

    // Mutable pointer to the field.
    pub fn mut_integer_value(&mut self) -> &mut Integer {
        if let ::std::option::Option::Some(field::Value::IntegerValue(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(field::Value::IntegerValue(Integer::new()));
        }
        match self.value {
            ::std::option::Option::Some(field::Value::IntegerValue(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_integer_value(&mut self) -> Integer {
        if self.has_integer_value() {
            match self.value.take() {
                ::std::option::Option::Some(field::Value::IntegerValue(v)) => v,
                _ => panic!(),
            }
        } else {
            Integer::new()
        }
    }

    // .laoflchdb.Bytes bytes_value = 3;

    pub fn bytes_value(&self) -> &Bytes {
        match self.value {
            ::std::option::Option::Some(field::Value::BytesValue(ref v)) => v,
            _ => <Bytes as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_bytes_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_bytes_value(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(field::Value::BytesValue(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_bytes_value(&mut self, v: Bytes) {
        self.value = ::std::option::Option::Some(field::Value::BytesValue(v))
    }

    // Mutable pointer to the field.
    pub fn mut_bytes_value(&mut self) -> &mut Bytes {
        if let ::std::option::Option::Some(field::Value::BytesValue(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(field::Value::BytesValue(Bytes::new()));
        }
        match self.value {
            ::std::option::Option::Some(field::Value::BytesValue(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_bytes_value(&mut self) -> Bytes {
        if self.has_bytes_value() {
            match self.value.take() {
                ::std::option::Option::Some(field::Value::BytesValue(v)) => v,
                _ => panic!(),
            }
        } else {
            Bytes::new()
        }
    }

    // .laoflchdb.Float float_value = 4;

    pub fn float_value(&self) -> &Float {
        match self.value {
            ::std::option::Option::Some(field::Value::FloatValue(ref v)) => v,
            _ => <Float as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_float_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_float_value(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(field::Value::FloatValue(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_float_value(&mut self, v: Float) {
        self.value = ::std::option::Option::Some(field::Value::FloatValue(v))
    }

    // Mutable pointer to the field.
    pub fn mut_float_value(&mut self) -> &mut Float {
        if let ::std::option::Option::Some(field::Value::FloatValue(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(field::Value::FloatValue(Float::new()));
        }
        match self.value {
            ::std::option::Option::Some(field::Value::FloatValue(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_float_value(&mut self) -> Float {
        if self.has_float_value() {
            match self.value.take() {
                ::std::option::Option::Some(field::Value::FloatValue(v)) => v,
                _ => panic!(),
            }
        } else {
            Float::new()
        }
    }

    // .laoflchdb.List list_value = 5;

    pub fn list_value(&self) -> &List {
        match self.value {
            ::std::option::Option::Some(field::Value::ListValue(ref v)) => v,
            _ => <List as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_list_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_list_value(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(field::Value::ListValue(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_list_value(&mut self, v: List) {
        self.value = ::std::option::Option::Some(field::Value::ListValue(v))
    }

    // Mutable pointer to the field.
    pub fn mut_list_value(&mut self) -> &mut List {
        if let ::std::option::Option::Some(field::Value::ListValue(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(field::Value::ListValue(List::new()));
        }
        match self.value {
            ::std::option::Option::Some(field::Value::ListValue(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_list_value(&mut self) -> List {
        if self.has_list_value() {
            match self.value.take() {
                ::std::option::Option::Some(field::Value::ListValue(v)) => v,
                _ => panic!(),
            }
        } else {
            List::new()
        }
    }

    // .laoflchdb.Image image_value = 6;

    pub fn image_value(&self) -> &Image {
        match self.value {
            ::std::option::Option::Some(field::Value::ImageValue(ref v)) => v,
            _ => <Image as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_image_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_image_value(&self) -> bool {
        match self.value {
            ::std::option::Option::Some(field::Value::ImageValue(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_image_value(&mut self, v: Image) {
        self.value = ::std::option::Option::Some(field::Value::ImageValue(v))
    }

    // Mutable pointer to the field.
    pub fn mut_image_value(&mut self) -> &mut Image {
        if let ::std::option::Option::Some(field::Value::ImageValue(_)) = self.value {
        } else {
            self.value = ::std::option::Option::Some(field::Value::ImageValue(Image::new()));
        }
        match self.value {
            ::std::option::Option::Some(field::Value::ImageValue(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_image_value(&mut self) -> Image {
        if self.has_image_value() {
            match self.value.take() {
                ::std::option::Option::Some(field::Value::ImageValue(v)) => v,
                _ => panic!(),
            }
        } else {
            Image::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, String>(
            "string_value",
            Field::has_string_value,
            Field::string_value,
            Field::mut_string_value,
            Field::set_string_value,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, Integer>(
            "integer_value",
            Field::has_integer_value,
            Field::integer_value,
            Field::mut_integer_value,
            Field::set_integer_value,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, Bytes>(
            "bytes_value",
            Field::has_bytes_value,
            Field::bytes_value,
            Field::mut_bytes_value,
            Field::set_bytes_value,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, Float>(
            "float_value",
            Field::has_float_value,
            Field::float_value,
            Field::mut_float_value,
            Field::set_float_value,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, List>(
            "list_value",
            Field::has_list_value,
            Field::list_value,
            Field::mut_list_value,
            Field::set_list_value,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, Image>(
            "image_value",
            Field::has_image_value,
            Field::image_value,
            Field::mut_image_value,
            Field::set_image_value,
        ));
        oneofs.push(field::Value::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Field>(
            "Field",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Field {
    const NAME: &'static str = "Field";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.value = ::std::option::Option::Some(field::Value::StringValue(is.read_message()?));
                },
                18 => {
                    self.value = ::std::option::Option::Some(field::Value::IntegerValue(is.read_message()?));
                },
                26 => {
                    self.value = ::std::option::Option::Some(field::Value::BytesValue(is.read_message()?));
                },
                34 => {
                    self.value = ::std::option::Option::Some(field::Value::FloatValue(is.read_message()?));
                },
                42 => {
                    self.value = ::std::option::Option::Some(field::Value::ListValue(is.read_message()?));
                },
                50 => {
                    self.value = ::std::option::Option::Some(field::Value::ImageValue(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.value {
            match v {
                &field::Value::StringValue(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &field::Value::IntegerValue(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &field::Value::BytesValue(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &field::Value::FloatValue(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &field::Value::ListValue(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &field::Value::ImageValue(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.value {
            match v {
                &field::Value::StringValue(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
                &field::Value::IntegerValue(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
                &field::Value::BytesValue(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
                &field::Value::FloatValue(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
                },
                &field::Value::ListValue(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
                },
                &field::Value::ImageValue(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Field {
        Field::new()
    }

    fn clear(&mut self) {
        self.value = ::std::option::Option::None;
        self.value = ::std::option::Option::None;
        self.value = ::std::option::Option::None;
        self.value = ::std::option::Option::None;
        self.value = ::std::option::Option::None;
        self.value = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Field {
        static instance: Field = Field {
            value: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Field {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Field").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Field {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Field {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `Field`
pub mod field {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:laoflchdb.Field.value)
    pub enum Value {
        // @@protoc_insertion_point(oneof_field:laoflchdb.Field.string_value)
        StringValue(super::String),
        // @@protoc_insertion_point(oneof_field:laoflchdb.Field.integer_value)
        IntegerValue(super::Integer),
        // @@protoc_insertion_point(oneof_field:laoflchdb.Field.bytes_value)
        BytesValue(super::Bytes),
        // @@protoc_insertion_point(oneof_field:laoflchdb.Field.float_value)
        FloatValue(super::Float),
        // @@protoc_insertion_point(oneof_field:laoflchdb.Field.list_value)
        ListValue(super::List),
        // @@protoc_insertion_point(oneof_field:laoflchdb.Field.image_value)
        ImageValue(super::Image),
    }

    impl ::protobuf::Oneof for Value {
    }

    impl ::protobuf::OneofFull for Value {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::Field as ::protobuf::MessageFull>::descriptor().oneof_by_name("value").unwrap()).clone()
        }
    }

    impl Value {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Value>("value")
        }
    }
}

// @@protoc_insertion_point(message:laoflchdb.String)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct String {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.String.value)
    pub value: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.String.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a String {
    fn default() -> &'a String {
        <String as ::protobuf::Message>::default_instance()
    }
}

impl String {
    pub fn new() -> String {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "value",
            |m: &String| { &m.value },
            |m: &mut String| { &mut m.value },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<String>(
            "String",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for String {
    const NAME: &'static str = "String";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.value = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.value);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.value.is_empty() {
            os.write_string(1, &self.value)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> String {
        String::new()
    }

    fn clear(&mut self) {
        self.value.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static String {
        static instance: String = String {
            value: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for String {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("String").unwrap()).clone()
    }
}

impl ::std::fmt::Display for String {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for String {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:laoflchdb.Integer)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Integer {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.Integer.value)
    pub value: i64,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.Integer.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Integer {
    fn default() -> &'a Integer {
        <Integer as ::protobuf::Message>::default_instance()
    }
}

impl Integer {
    pub fn new() -> Integer {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "value",
            |m: &Integer| { &m.value },
            |m: &mut Integer| { &mut m.value },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Integer>(
            "Integer",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Integer {
    const NAME: &'static str = "Integer";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.value = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.value != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.value);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.value != 0 {
            os.write_int64(1, self.value)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Integer {
        Integer::new()
    }

    fn clear(&mut self) {
        self.value = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Integer {
        static instance: Integer = Integer {
            value: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Integer {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Integer").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Integer {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Integer {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:laoflchdb.Bytes)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Bytes {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.Bytes.value)
    pub value: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.Bytes.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Bytes {
    fn default() -> &'a Bytes {
        <Bytes as ::protobuf::Message>::default_instance()
    }
}

impl Bytes {
    pub fn new() -> Bytes {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "value",
            |m: &Bytes| { &m.value },
            |m: &mut Bytes| { &mut m.value },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Bytes>(
            "Bytes",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Bytes {
    const NAME: &'static str = "Bytes";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.value = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.value);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.value.is_empty() {
            os.write_bytes(1, &self.value)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Bytes {
        Bytes::new()
    }

    fn clear(&mut self) {
        self.value.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Bytes {
        static instance: Bytes = Bytes {
            value: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Bytes {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Bytes").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Bytes {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Bytes {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:laoflchdb.Float)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Float {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.Float.value)
    pub value: f64,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.Float.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Float {
    fn default() -> &'a Float {
        <Float as ::protobuf::Message>::default_instance()
    }
}

impl Float {
    pub fn new() -> Float {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "value",
            |m: &Float| { &m.value },
            |m: &mut Float| { &mut m.value },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Float>(
            "Float",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Float {
    const NAME: &'static str = "Float";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                9 => {
                    self.value = is.read_double()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.value != 0. {
            my_size += 1 + 8;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.value != 0. {
            os.write_double(1, self.value)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Float {
        Float::new()
    }

    fn clear(&mut self) {
        self.value = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Float {
        static instance: Float = Float {
            value: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Float {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Float").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Float {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Float {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:laoflchdb.List)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct List {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.List.items)
    pub items: ::std::vec::Vec<::std::vec::Vec<u8>>,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.List.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a List {
    fn default() -> &'a List {
        <List as ::protobuf::Message>::default_instance()
    }
}

impl List {
    pub fn new() -> List {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "items",
            |m: &List| { &m.items },
            |m: &mut List| { &mut m.items },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<List>(
            "List",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for List {
    const NAME: &'static str = "List";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.items.push(is.read_bytes()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.items {
            my_size += ::protobuf::rt::bytes_size(1, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.items {
            os.write_bytes(1, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> List {
        List::new()
    }

    fn clear(&mut self) {
        self.items.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static List {
        static instance: List = List {
            items: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for List {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("List").unwrap()).clone()
    }
}

impl ::std::fmt::Display for List {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for List {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:laoflchdb.Image)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Image {
    // message fields
    // @@protoc_insertion_point(field:laoflchdb.Image.data)
    pub data: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:laoflchdb.Image.format)
    pub format: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:laoflchdb.Image.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Image {
    fn default() -> &'a Image {
        <Image as ::protobuf::Message>::default_instance()
    }
}

impl Image {
    pub fn new() -> Image {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &Image| { &m.data },
            |m: &mut Image| { &mut m.data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "format",
            |m: &Image| { &m.format },
            |m: &mut Image| { &mut m.format },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Image>(
            "Image",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Image {
    const NAME: &'static str = "Image";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.data = is.read_bytes()?;
                },
                18 => {
                    self.format = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.data);
        }
        if !self.format.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.format);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.data.is_empty() {
            os.write_bytes(1, &self.data)?;
        }
        if !self.format.is_empty() {
            os.write_string(2, &self.format)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Image {
        Image::new()
    }

    fn clear(&mut self) {
        self.data.clear();
        self.format.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Image {
        static instance: Image = Image {
            data: ::std::vec::Vec::new(),
            format: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Image {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Image").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Image {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Image {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bfield.proto\x12\tlaoflchdb\"\xd4\x02\n\x05Field\x126\n\x0cstring_v\
    alue\x18\x01\x20\x01(\x0b2\x11.laoflchdb.StringH\0R\x0bstringValue\x129\
    \n\rinteger_value\x18\x02\x20\x01(\x0b2\x12.laoflchdb.IntegerH\0R\x0cint\
    egerValue\x123\n\x0bbytes_value\x18\x03\x20\x01(\x0b2\x10.laoflchdb.Byte\
    sH\0R\nbytesValue\x123\n\x0bfloat_value\x18\x04\x20\x01(\x0b2\x10.laoflc\
    hdb.FloatH\0R\nfloatValue\x120\n\nlist_value\x18\x05\x20\x01(\x0b2\x0f.l\
    aoflchdb.ListH\0R\tlistValue\x123\n\x0bimage_value\x18\x06\x20\x01(\x0b2\
    \x10.laoflchdb.ImageH\0R\nimageValueB\x07\n\x05value\"\x1e\n\x06String\
    \x12\x14\n\x05value\x18\x01\x20\x01(\tR\x05value\"\x1f\n\x07Integer\x12\
    \x14\n\x05value\x18\x01\x20\x01(\x03R\x05value\"\x1d\n\x05Bytes\x12\x14\
    \n\x05value\x18\x01\x20\x01(\x0cR\x05value\"\x1d\n\x05Float\x12\x14\n\
    \x05value\x18\x01\x20\x01(\x01R\x05value\"\x1c\n\x04List\x12\x14\n\x05it\
    ems\x18\x01\x20\x03(\x0cR\x05items\"3\n\x05Image\x12\x12\n\x04data\x18\
    \x01\x20\x01(\x0cR\x04data\x12\x16\n\x06format\x18\x02\x20\x01(\tR\x06fo\
    rmatJ\xb9\x07\n\x06\x12\x04\0\0&\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\
    \x08\n\x01\x02\x12\x03\x02\0\x12\n\n\n\x02\x04\0\x12\x04\x04\0\r\x01\n\n\
    \n\x03\x04\0\x01\x12\x03\x04\x08\r\n\x0c\n\x04\x04\0\x08\0\x12\x04\x05\
    \x04\x0c\x05\n\x0c\n\x05\x04\0\x08\0\x01\x12\x03\x05\n\x0f\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03\x06\x08\x20\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\x06\
    \x08\x0e\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x06\x0f\x1b\n\x0c\n\x05\x04\
    \0\x02\0\x03\x12\x03\x06\x1e\x1f\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x07\
    \x08\"\n\x0c\n\x05\x04\0\x02\x01\x06\x12\x03\x07\x08\x0f\n\x0c\n\x05\x04\
    \0\x02\x01\x01\x12\x03\x07\x10\x1d\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\
    \x07\x20!\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x08\x08\x1e\n\x0c\n\x05\x04\
    \0\x02\x02\x06\x12\x03\x08\x08\r\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\
    \x08\x0e\x19\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x08\x1c\x1d\n\x0b\n\
    \x04\x04\0\x02\x03\x12\x03\t\x08\x1e\n\x0c\n\x05\x04\0\x02\x03\x06\x12\
    \x03\t\x08\r\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\t\x0e\x19\n\x0c\n\x05\
    \x04\0\x02\x03\x03\x12\x03\t\x1c\x1d\n\x0b\n\x04\x04\0\x02\x04\x12\x03\n\
    \x08\x1c\n\x0c\n\x05\x04\0\x02\x04\x06\x12\x03\n\x08\x0c\n\x0c\n\x05\x04\
    \0\x02\x04\x01\x12\x03\n\r\x17\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\n\
    \x1a\x1b\n\x0b\n\x04\x04\0\x02\x05\x12\x03\x0b\x08\x1e\n\x0c\n\x05\x04\0\
    \x02\x05\x06\x12\x03\x0b\x08\r\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\x0b\
    \x0e\x19\n\x0c\n\x05\x04\0\x02\x05\x03\x12\x03\x0b\x1c\x1d\n\n\n\x02\x04\
    \x01\x12\x04\x0f\0\x11\x01\n\n\n\x03\x04\x01\x01\x12\x03\x0f\x08\x0e\n\
    \x0b\n\x04\x04\x01\x02\0\x12\x03\x10\x04\x15\n\x0c\n\x05\x04\x01\x02\0\
    \x05\x12\x03\x10\x04\n\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x10\x0b\x10\
    \n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x10\x13\x14\n\n\n\x02\x04\x02\x12\
    \x04\x13\0\x15\x01\n\n\n\x03\x04\x02\x01\x12\x03\x13\x08\x0f\n\x0b\n\x04\
    \x04\x02\x02\0\x12\x03\x14\x04\x14\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\
    \x14\x04\t\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x14\n\x0f\n\x0c\n\x05\
    \x04\x02\x02\0\x03\x12\x03\x14\x12\x13\n\n\n\x02\x04\x03\x12\x04\x17\0\
    \x19\x01\n\n\n\x03\x04\x03\x01\x12\x03\x17\x08\r\n\x0b\n\x04\x04\x03\x02\
    \0\x12\x03\x18\x04\x14\n\x0c\n\x05\x04\x03\x02\0\x05\x12\x03\x18\x04\t\n\
    \x0c\n\x05\x04\x03\x02\0\x01\x12\x03\x18\n\x0f\n\x0c\n\x05\x04\x03\x02\0\
    \x03\x12\x03\x18\x12\x13\n\n\n\x02\x04\x04\x12\x04\x1b\0\x1d\x01\n\n\n\
    \x03\x04\x04\x01\x12\x03\x1b\x08\r\n\x0b\n\x04\x04\x04\x02\0\x12\x03\x1c\
    \x04\x15\n\x0c\n\x05\x04\x04\x02\0\x05\x12\x03\x1c\x04\n\n\x0c\n\x05\x04\
    \x04\x02\0\x01\x12\x03\x1c\x0b\x10\n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03\
    \x1c\x13\x14\n\n\n\x02\x04\x05\x12\x04\x1f\0!\x01\n\n\n\x03\x04\x05\x01\
    \x12\x03\x1f\x08\x0c\n\x0b\n\x04\x04\x05\x02\0\x12\x03\x20\x04\x1d\n\x0c\
    \n\x05\x04\x05\x02\0\x04\x12\x03\x20\x04\x0c\n\x0c\n\x05\x04\x05\x02\0\
    \x05\x12\x03\x20\r\x12\n\x0c\n\x05\x04\x05\x02\0\x01\x12\x03\x20\x13\x18\
    \n\x0c\n\x05\x04\x05\x02\0\x03\x12\x03\x20\x1b\x1c\n\n\n\x02\x04\x06\x12\
    \x04#\0&\x01\n\n\n\x03\x04\x06\x01\x12\x03#\x08\r\n\x0b\n\x04\x04\x06\
    \x02\0\x12\x03$\x04\x13\n\x0c\n\x05\x04\x06\x02\0\x05\x12\x03$\x04\t\n\
    \x0c\n\x05\x04\x06\x02\0\x01\x12\x03$\n\x0e\n\x0c\n\x05\x04\x06\x02\0\
    \x03\x12\x03$\x11\x12\n\x0b\n\x04\x04\x06\x02\x01\x12\x03%\x04\x16\n\x0c\
    \n\x05\x04\x06\x02\x01\x05\x12\x03%\x04\n\n\x0c\n\x05\x04\x06\x02\x01\
    \x01\x12\x03%\x0b\x11\n\x0c\n\x05\x04\x06\x02\x01\x03\x12\x03%\x14\x15b\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(7);
            messages.push(Field::generated_message_descriptor_data());
            messages.push(String::generated_message_descriptor_data());
            messages.push(Integer::generated_message_descriptor_data());
            messages.push(Bytes::generated_message_descriptor_data());
            messages.push(Float::generated_message_descriptor_data());
            messages.push(List::generated_message_descriptor_data());
            messages.push(Image::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
