# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingIndexServiceStub(object):
    """─────────────────────────────────────────────
    HNSW 向量索引服务
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertEmbedding = channel.unary_unary(
                '/laoflchdb.embedding.EmbeddingIndexService/InsertEmbedding',
                request_serializer=embedding__pb2.InsertEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.InsertEmbeddingResponse.FromString,
                _registered_method=True)
        self.SearchEmbedding = channel.unary_unary(
                '/laoflchdb.embedding.EmbeddingIndexService/SearchEmbedding',
                request_serializer=embedding__pb2.SearchEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.SearchEmbeddingResponse.FromString,
                _registered_method=True)
        self.DeleteEmbedding = channel.unary_unary(
                '/laoflchdb.embedding.EmbeddingIndexService/DeleteEmbedding',
                request_serializer=embedding__pb2.DeleteEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.DeleteEmbeddingResponse.FromString,
                _registered_method=True)
        self.GetIndexInfo = channel.unary_unary(
                '/laoflchdb.embedding.EmbeddingIndexService/GetIndexInfo',
                request_serializer=embedding__pb2.GetIndexInfoRequest.SerializeToString,
                response_deserializer=embedding__pb2.GetIndexInfoResponse.FromString,
                _registered_method=True)
        self.SaveSnapshot = channel.unary_unary(
                '/laoflchdb.embedding.EmbeddingIndexService/SaveSnapshot',
                request_serializer=embedding__pb2.SaveSnapshotRequest.SerializeToString,
                response_deserializer=embedding__pb2.SaveSnapshotResponse.FromString,
                _registered_method=True)
        self.LoadSnapshot = channel.unary_unary(
                '/laoflchdb.embedding.EmbeddingIndexService/LoadSnapshot',
                request_serializer=embedding__pb2.LoadSnapshotRequest.SerializeToString,
                response_deserializer=embedding__pb2.LoadSnapshotResponse.FromString,
                _registered_method=True)


class EmbeddingIndexServiceServicer(object):
    """─────────────────────────────────────────────
    HNSW 向量索引服务
    ─────────────────────────────────────────────

    """

    def InsertEmbedding(self, request, context):
        """插入向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEmbedding(self, request, context):
        """搜索最近邻
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEmbedding(self, request, context):
        """删除向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexInfo(self, request, context):
        """获取索引信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSnapshot(self, request, context):
        """手动保存快照
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSnapshot(self, request, context):
        """手动加载快照
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingIndexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertEmbedding,
                    request_deserializer=embedding__pb2.InsertEmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.InsertEmbeddingResponse.SerializeToString,
            ),
            'SearchEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEmbedding,
                    request_deserializer=embedding__pb2.SearchEmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.SearchEmbeddingResponse.SerializeToString,
            ),
            'DeleteEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEmbedding,
                    request_deserializer=embedding__pb2.DeleteEmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.DeleteEmbeddingResponse.SerializeToString,
            ),
            'GetIndexInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexInfo,
                    request_deserializer=embedding__pb2.GetIndexInfoRequest.FromString,
                    response_serializer=embedding__pb2.GetIndexInfoResponse.SerializeToString,
            ),
            'SaveSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveSnapshot,
                    request_deserializer=embedding__pb2.SaveSnapshotRequest.FromString,
                    response_serializer=embedding__pb2.SaveSnapshotResponse.SerializeToString,
            ),
            'LoadSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSnapshot,
                    request_deserializer=embedding__pb2.LoadSnapshotRequest.FromString,
                    response_serializer=embedding__pb2.LoadSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laoflchdb.embedding.EmbeddingIndexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laoflchdb.embedding.EmbeddingIndexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingIndexService(object):
    """─────────────────────────────────────────────
    HNSW 向量索引服务
    ─────────────────────────────────────────────

    """

    @staticmethod
    def InsertEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.embedding.EmbeddingIndexService/InsertEmbedding',
            embedding__pb2.InsertEmbeddingRequest.SerializeToString,
            embedding__pb2.InsertEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.embedding.EmbeddingIndexService/SearchEmbedding',
            embedding__pb2.SearchEmbeddingRequest.SerializeToString,
            embedding__pb2.SearchEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.embedding.EmbeddingIndexService/DeleteEmbedding',
            embedding__pb2.DeleteEmbeddingRequest.SerializeToString,
            embedding__pb2.DeleteEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.embedding.EmbeddingIndexService/GetIndexInfo',
            embedding__pb2.GetIndexInfoRequest.SerializeToString,
            embedding__pb2.GetIndexInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.embedding.EmbeddingIndexService/SaveSnapshot',
            embedding__pb2.SaveSnapshotRequest.SerializeToString,
            embedding__pb2.SaveSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.embedding.EmbeddingIndexService/LoadSnapshot',
            embedding__pb2.LoadSnapshotRequest.SerializeToString,
            embedding__pb2.LoadSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
