# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import face_service_pb2 as face__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in face_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceServiceStub(object):
    """人脸服务 - 基于 SCRFD 人脸检测 + 5 关键点仿射对齐 + ArcFace 特征提取
    支持从图片中检测人脸、对齐裁剪 112x112、提取 512 维 L2 归一化特征
    可选通过 image_service 保存对齐后的人脸图片
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectFaces = channel.unary_unary(
                '/laoflchdb.face_service.FaceService/DetectFaces',
                request_serializer=face__service__pb2.DetectFacesRequest.SerializeToString,
                response_deserializer=face__service__pb2.DetectFacesResponse.FromString,
                _registered_method=True)
        self.ExtractFaceFeatures = channel.unary_unary(
                '/laoflchdb.face_service.FaceService/ExtractFaceFeatures',
                request_serializer=face__service__pb2.ExtractFaceFeaturesRequest.SerializeToString,
                response_deserializer=face__service__pb2.ExtractFaceFeaturesResponse.FromString,
                _registered_method=True)
        self.ExtractFeatureFromAligned = channel.unary_unary(
                '/laoflchdb.face_service.FaceService/ExtractFeatureFromAligned',
                request_serializer=face__service__pb2.ExtractFeatureFromAlignedRequest.SerializeToString,
                response_deserializer=face__service__pb2.ExtractFeatureFromAlignedResponse.FromString,
                _registered_method=True)
        self.CompareFeatures = channel.unary_unary(
                '/laoflchdb.face_service.FaceService/CompareFeatures',
                request_serializer=face__service__pb2.CompareFeaturesRequest.SerializeToString,
                response_deserializer=face__service__pb2.CompareFeaturesResponse.FromString,
                _registered_method=True)


class FaceServiceServicer(object):
    """人脸服务 - 基于 SCRFD 人脸检测 + 5 关键点仿射对齐 + ArcFace 特征提取
    支持从图片中检测人脸、对齐裁剪 112x112、提取 512 维 L2 归一化特征
    可选通过 image_service 保存对齐后的人脸图片
    """

    def DetectFaces(self, request, context):
        """检测人脸：从图片中检测所有人脸，返回人脸框和 5 个关键点
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractFaceFeatures(self, request, context):
        """提取人脸特征：检测人脸 → 对齐裁剪 112x112 → ArcFace 提取 512 维特征 → L2 归一化
        可选保存对齐后的人脸图片到 image_service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractFeatureFromAligned(self, request, context):
        """对已对齐的 112x112 人脸图片直接提取特征（跳过检测和对齐）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareFeatures(self, request, context):
        """比较两个人脸特征向量的相似度（余弦相似度）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFaces,
                    request_deserializer=face__service__pb2.DetectFacesRequest.FromString,
                    response_serializer=face__service__pb2.DetectFacesResponse.SerializeToString,
            ),
            'ExtractFaceFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractFaceFeatures,
                    request_deserializer=face__service__pb2.ExtractFaceFeaturesRequest.FromString,
                    response_serializer=face__service__pb2.ExtractFaceFeaturesResponse.SerializeToString,
            ),
            'ExtractFeatureFromAligned': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractFeatureFromAligned,
                    request_deserializer=face__service__pb2.ExtractFeatureFromAlignedRequest.FromString,
                    response_serializer=face__service__pb2.ExtractFeatureFromAlignedResponse.SerializeToString,
            ),
            'CompareFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareFeatures,
                    request_deserializer=face__service__pb2.CompareFeaturesRequest.FromString,
                    response_serializer=face__service__pb2.CompareFeaturesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laoflchdb.face_service.FaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laoflchdb.face_service.FaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceService(object):
    """人脸服务 - 基于 SCRFD 人脸检测 + 5 关键点仿射对齐 + ArcFace 特征提取
    支持从图片中检测人脸、对齐裁剪 112x112、提取 512 维 L2 归一化特征
    可选通过 image_service 保存对齐后的人脸图片
    """

    @staticmethod
    def DetectFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.face_service.FaceService/DetectFaces',
            face__service__pb2.DetectFacesRequest.SerializeToString,
            face__service__pb2.DetectFacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractFaceFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.face_service.FaceService/ExtractFaceFeatures',
            face__service__pb2.ExtractFaceFeaturesRequest.SerializeToString,
            face__service__pb2.ExtractFaceFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractFeatureFromAligned(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.face_service.FaceService/ExtractFeatureFromAligned',
            face__service__pb2.ExtractFeatureFromAlignedRequest.SerializeToString,
            face__service__pb2.ExtractFeatureFromAlignedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.face_service.FaceService/CompareFeatures',
            face__service__pb2.CompareFeaturesRequest.SerializeToString,
            face__service__pb2.CompareFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
