# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: field.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'field.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66ield.proto\x12\tlaoflchdb\"\x8a\x02\n\x05\x46ield\x12)\n\x0cstring_value\x18\x01 \x01(\x0b\x32\x11.laoflchdb.StringH\x00\x12+\n\rinteger_value\x18\x02 \x01(\x0b\x32\x12.laoflchdb.IntegerH\x00\x12\'\n\x0b\x62ytes_value\x18\x03 \x01(\x0b\x32\x10.laoflchdb.BytesH\x00\x12\'\n\x0b\x66loat_value\x18\x04 \x01(\x0b\x32\x10.laoflchdb.FloatH\x00\x12%\n\nlist_value\x18\x05 \x01(\x0b\x32\x0f.laoflchdb.ListH\x00\x12\'\n\x0bimage_value\x18\x06 \x01(\x0b\x32\x10.laoflchdb.ImageH\x00\x42\x07\n\x05value\"\x17\n\x06String\x12\r\n\x05value\x18\x01 \x01(\t\"\x18\n\x07Integer\x12\r\n\x05value\x18\x01 \x01(\x03\"\x16\n\x05\x42ytes\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x16\n\x05\x46loat\x12\r\n\x05value\x18\x01 \x01(\x01\"\x15\n\x04List\x12\r\n\x05items\x18\x01 \x03(\x0c\"%\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'field_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIELD']._serialized_start=27
  _globals['_FIELD']._serialized_end=293
  _globals['_STRING']._serialized_start=295
  _globals['_STRING']._serialized_end=318
  _globals['_INTEGER']._serialized_start=320
  _globals['_INTEGER']._serialized_end=344
  _globals['_BYTES']._serialized_start=346
  _globals['_BYTES']._serialized_end=368
  _globals['_FLOAT']._serialized_start=370
  _globals['_FLOAT']._serialized_end=392
  _globals['_LIST']._serialized_start=394
  _globals['_LIST']._serialized_end=415
  _globals['_IMAGE']._serialized_start=417
  _globals['_IMAGE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
