# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import image_service_pb2 as image__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in image_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageServiceStub(object):
    """图片服务 - 基于对象存储实现图片上传（自动生成三种缩略图）和浏览
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadImage = channel.unary_unary(
                '/laoflchdb.image_service.ImageService/UploadImage',
                request_serializer=image__service__pb2.UploadImageRequest.SerializeToString,
                response_deserializer=image__service__pb2.UploadImageResponse.FromString,
                _registered_method=True)
        self.GetImage = channel.unary_unary(
                '/laoflchdb.image_service.ImageService/GetImage',
                request_serializer=image__service__pb2.GetImageRequest.SerializeToString,
                response_deserializer=image__service__pb2.GetImageResponse.FromString,
                _registered_method=True)
        self.GetThumbnail = channel.unary_unary(
                '/laoflchdb.image_service.ImageService/GetThumbnail',
                request_serializer=image__service__pb2.GetThumbnailRequest.SerializeToString,
                response_deserializer=image__service__pb2.GetThumbnailResponse.FromString,
                _registered_method=True)
        self.GetImageMetadata = channel.unary_unary(
                '/laoflchdb.image_service.ImageService/GetImageMetadata',
                request_serializer=image__service__pb2.GetImageMetadataRequest.SerializeToString,
                response_deserializer=image__service__pb2.GetImageMetadataResponse.FromString,
                _registered_method=True)
        self.ListImages = channel.unary_unary(
                '/laoflchdb.image_service.ImageService/ListImages',
                request_serializer=image__service__pb2.ListImagesRequest.SerializeToString,
                response_deserializer=image__service__pb2.ListImagesResponse.FromString,
                _registered_method=True)
        self.DeleteImage = channel.unary_unary(
                '/laoflchdb.image_service.ImageService/DeleteImage',
                request_serializer=image__service__pb2.DeleteImageRequest.SerializeToString,
                response_deserializer=image__service__pb2.DeleteImageResponse.FromString,
                _registered_method=True)
        self.UploadImageStream = channel.stream_unary(
                '/laoflchdb.image_service.ImageService/UploadImageStream',
                request_serializer=image__service__pb2.UploadImageChunk.SerializeToString,
                response_deserializer=image__service__pb2.UploadImageResponse.FromString,
                _registered_method=True)


class ImageServiceServicer(object):
    """图片服务 - 基于对象存储实现图片上传（自动生成三种缩略图）和浏览
    """

    def UploadImage(self, request, context):
        """上传图片（自动生成 thumbnail/small/medium 三种缩略图，并保存图片元数据）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """获取原图
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThumbnail(self, request, context):
        """获取缩略图（size: thumbnail/small/medium）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImageMetadata(self, request, context):
        """获取图片元数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListImages(self, request, context):
        """列出图片（支持前缀过滤和分页）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteImage(self, request, context):
        """删除图片（同时删除原图和所有缩略图及元数据）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadImageStream(self, request_iterator, context):
        """流式上传图片（支持大文件切片上传）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=image__service__pb2.UploadImageRequest.FromString,
                    response_serializer=image__service__pb2.UploadImageResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=image__service__pb2.GetImageRequest.FromString,
                    response_serializer=image__service__pb2.GetImageResponse.SerializeToString,
            ),
            'GetThumbnail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThumbnail,
                    request_deserializer=image__service__pb2.GetThumbnailRequest.FromString,
                    response_serializer=image__service__pb2.GetThumbnailResponse.SerializeToString,
            ),
            'GetImageMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageMetadata,
                    request_deserializer=image__service__pb2.GetImageMetadataRequest.FromString,
                    response_serializer=image__service__pb2.GetImageMetadataResponse.SerializeToString,
            ),
            'ListImages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListImages,
                    request_deserializer=image__service__pb2.ListImagesRequest.FromString,
                    response_serializer=image__service__pb2.ListImagesResponse.SerializeToString,
            ),
            'DeleteImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteImage,
                    request_deserializer=image__service__pb2.DeleteImageRequest.FromString,
                    response_serializer=image__service__pb2.DeleteImageResponse.SerializeToString,
            ),
            'UploadImageStream': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadImageStream,
                    request_deserializer=image__service__pb2.UploadImageChunk.FromString,
                    response_serializer=image__service__pb2.UploadImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laoflchdb.image_service.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laoflchdb.image_service.ImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """图片服务 - 基于对象存储实现图片上传（自动生成三种缩略图）和浏览
    """

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.image_service.ImageService/UploadImage',
            image__service__pb2.UploadImageRequest.SerializeToString,
            image__service__pb2.UploadImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.image_service.ImageService/GetImage',
            image__service__pb2.GetImageRequest.SerializeToString,
            image__service__pb2.GetImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThumbnail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.image_service.ImageService/GetThumbnail',
            image__service__pb2.GetThumbnailRequest.SerializeToString,
            image__service__pb2.GetThumbnailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImageMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.image_service.ImageService/GetImageMetadata',
            image__service__pb2.GetImageMetadataRequest.SerializeToString,
            image__service__pb2.GetImageMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.image_service.ImageService/ListImages',
            image__service__pb2.ListImagesRequest.SerializeToString,
            image__service__pb2.ListImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.image_service.ImageService/DeleteImage',
            image__service__pb2.DeleteImageRequest.SerializeToString,
            image__service__pb2.DeleteImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadImageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/laoflchdb.image_service.ImageService/UploadImageStream',
            image__service__pb2.UploadImageChunk.SerializeToString,
            image__service__pb2.UploadImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
