# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import object_store_pb2 as object__store__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in object_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectStoreServiceStub(object):
    """S3 兼容的对象存储服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutObject = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/PutObject',
                request_serializer=object__store__pb2.PutObjectRequest.SerializeToString,
                response_deserializer=object__store__pb2.PutObjectResponse.FromString,
                _registered_method=True)
        self.GetObject = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/GetObject',
                request_serializer=object__store__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=object__store__pb2.GetObjectResponse.FromString,
                _registered_method=True)
        self.DeleteObject = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/DeleteObject',
                request_serializer=object__store__pb2.DeleteObjectRequest.SerializeToString,
                response_deserializer=object__store__pb2.DeleteObjectResponse.FromString,
                _registered_method=True)
        self.ListObjects = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/ListObjects',
                request_serializer=object__store__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=object__store__pb2.ListObjectsResponse.FromString,
                _registered_method=True)
        self.HeadObject = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/HeadObject',
                request_serializer=object__store__pb2.HeadObjectRequest.SerializeToString,
                response_deserializer=object__store__pb2.HeadObjectResponse.FromString,
                _registered_method=True)
        self.CopyObject = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/CopyObject',
                request_serializer=object__store__pb2.CopyObjectRequest.SerializeToString,
                response_deserializer=object__store__pb2.CopyObjectResponse.FromString,
                _registered_method=True)
        self.DeleteObjects = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/DeleteObjects',
                request_serializer=object__store__pb2.DeleteObjectsRequest.SerializeToString,
                response_deserializer=object__store__pb2.DeleteObjectsResponse.FromString,
                _registered_method=True)
        self.CreateBucket = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/CreateBucket',
                request_serializer=object__store__pb2.CreateBucketRequest.SerializeToString,
                response_deserializer=object__store__pb2.CreateBucketResponse.FromString,
                _registered_method=True)
        self.DeleteBucket = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/DeleteBucket',
                request_serializer=object__store__pb2.DeleteBucketRequest.SerializeToString,
                response_deserializer=object__store__pb2.DeleteBucketResponse.FromString,
                _registered_method=True)
        self.ListBuckets = channel.unary_unary(
                '/laoflchdb.object_store.ObjectStoreService/ListBuckets',
                request_serializer=object__store__pb2.ListBucketsRequest.SerializeToString,
                response_deserializer=object__store__pb2.ListBucketsResponse.FromString,
                _registered_method=True)


class ObjectStoreServiceServicer(object):
    """S3 兼容的对象存储服务
    """

    def PutObject(self, request, context):
        """存储对象（PutObject）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """获取对象（GetObject）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """删除对象（DeleteObject）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """列出对象（ListObjects）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeadObject(self, request, context):
        """获取对象元数据（HeadObject）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyObject(self, request, context):
        """复制对象（CopyObject）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObjects(self, request, context):
        """批量删除对象（DeleteObjects）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBucket(self, request, context):
        """创建存储桶（CreateBucket）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBucket(self, request, context):
        """删除存储桶（DeleteBucket）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBuckets(self, request, context):
        """列出存储桶（ListBuckets）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutObject': grpc.unary_unary_rpc_method_handler(
                    servicer.PutObject,
                    request_deserializer=object__store__pb2.PutObjectRequest.FromString,
                    response_serializer=object__store__pb2.PutObjectResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=object__store__pb2.GetObjectRequest.FromString,
                    response_serializer=object__store__pb2.GetObjectResponse.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=object__store__pb2.DeleteObjectRequest.FromString,
                    response_serializer=object__store__pb2.DeleteObjectResponse.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=object__store__pb2.ListObjectsRequest.FromString,
                    response_serializer=object__store__pb2.ListObjectsResponse.SerializeToString,
            ),
            'HeadObject': grpc.unary_unary_rpc_method_handler(
                    servicer.HeadObject,
                    request_deserializer=object__store__pb2.HeadObjectRequest.FromString,
                    response_serializer=object__store__pb2.HeadObjectResponse.SerializeToString,
            ),
            'CopyObject': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyObject,
                    request_deserializer=object__store__pb2.CopyObjectRequest.FromString,
                    response_serializer=object__store__pb2.CopyObjectResponse.SerializeToString,
            ),
            'DeleteObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObjects,
                    request_deserializer=object__store__pb2.DeleteObjectsRequest.FromString,
                    response_serializer=object__store__pb2.DeleteObjectsResponse.SerializeToString,
            ),
            'CreateBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBucket,
                    request_deserializer=object__store__pb2.CreateBucketRequest.FromString,
                    response_serializer=object__store__pb2.CreateBucketResponse.SerializeToString,
            ),
            'DeleteBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBucket,
                    request_deserializer=object__store__pb2.DeleteBucketRequest.FromString,
                    response_serializer=object__store__pb2.DeleteBucketResponse.SerializeToString,
            ),
            'ListBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBuckets,
                    request_deserializer=object__store__pb2.ListBucketsRequest.FromString,
                    response_serializer=object__store__pb2.ListBucketsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laoflchdb.object_store.ObjectStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laoflchdb.object_store.ObjectStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectStoreService(object):
    """S3 兼容的对象存储服务
    """

    @staticmethod
    def PutObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/PutObject',
            object__store__pb2.PutObjectRequest.SerializeToString,
            object__store__pb2.PutObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/GetObject',
            object__store__pb2.GetObjectRequest.SerializeToString,
            object__store__pb2.GetObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/DeleteObject',
            object__store__pb2.DeleteObjectRequest.SerializeToString,
            object__store__pb2.DeleteObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/ListObjects',
            object__store__pb2.ListObjectsRequest.SerializeToString,
            object__store__pb2.ListObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeadObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/HeadObject',
            object__store__pb2.HeadObjectRequest.SerializeToString,
            object__store__pb2.HeadObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/CopyObject',
            object__store__pb2.CopyObjectRequest.SerializeToString,
            object__store__pb2.CopyObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/DeleteObjects',
            object__store__pb2.DeleteObjectsRequest.SerializeToString,
            object__store__pb2.DeleteObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/CreateBucket',
            object__store__pb2.CreateBucketRequest.SerializeToString,
            object__store__pb2.CreateBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/DeleteBucket',
            object__store__pb2.DeleteBucketRequest.SerializeToString,
            object__store__pb2.DeleteBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.object_store.ObjectStoreService/ListBuckets',
            object__store__pb2.ListBucketsRequest.SerializeToString,
            object__store__pb2.ListBucketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
