# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import field_pb2 as field__pb2
import row_pb2 as row__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\tlaoflchdb\x1a\x0b\x66ield.proto\x1a\trow.proto\"Y\n\x0c\x43olumnFilter\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x34\n\nconditions\x18\x02 \x03(\x0b\x32 .laoflchdb.ColumnFilterCondition\"\x81\x01\n\x15\x43olumnFilterCondition\x12%\n\x02op\x18\x01 \x01(\x0e\x32\x19.laoflchdb.FilterOperator\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.laoflchdb.Field\x12 \n\x06values\x18\x03 \x03(\x0b\x32\x10.laoflchdb.Field\"R\n\x0bTableFilter\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12/\n\x0e\x63olumn_filters\x18\x02 \x03(\x0b\x32\x17.laoflchdb.ColumnFilter\"\x8f\x01\n\x05Query\x12-\n\rtable_filters\x18\x01 \x03(\x0b\x32\x16.laoflchdb.TableFilter\x12\x12\n\x05limit\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x13\n\x06offset\x18\x03 \x01(\rH\x01\x88\x01\x01\x12\x19\n\x11projected_columns\x18\x04 \x03(\tB\x08\n\x06_limitB\t\n\x07_offset\"0\n\x0bQueryResult\x12!\n\x04rows\x18\x01 \x03(\x0b\x32\x13.laoflchdb.QueryRow\"K\n\x08QueryRow\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12\x0e\n\x06row_id\x18\x02 \x01(\x04\x12\x1b\n\x03row\x18\x03 \x01(\x0b\x32\x0e.laoflchdb.Row*\xd0\x02\n\x0e\x46ilterOperator\x12\x1f\n\x1b\x46ILTER_OPERATOR_UNSPECIFIED\x10\x00\x12\x16\n\x12\x46ILTER_OPERATOR_EQ\x10\x01\x12\x17\n\x13\x46ILTER_OPERATOR_NEQ\x10\x02\x12\x16\n\x12\x46ILTER_OPERATOR_GT\x10\x03\x12\x17\n\x13\x46ILTER_OPERATOR_GTE\x10\x04\x12\x16\n\x12\x46ILTER_OPERATOR_LT\x10\x05\x12\x17\n\x13\x46ILTER_OPERATOR_LTE\x10\x06\x12\x16\n\x12\x46ILTER_OPERATOR_IN\x10\x07\x12\x1a\n\x16\x46ILTER_OPERATOR_NOT_IN\x10\x08\x12\x18\n\x14\x46ILTER_OPERATOR_LIKE\x10\t\x12\x1b\n\x17\x46ILTER_OPERATOR_IS_NULL\x10\n\x12\x1f\n\x1b\x46ILTER_OPERATOR_IS_NOT_NULL\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILTEROPERATOR']._serialized_start=631
  _globals['_FILTEROPERATOR']._serialized_end=967
  _globals['_COLUMNFILTER']._serialized_start=50
  _globals['_COLUMNFILTER']._serialized_end=139
  _globals['_COLUMNFILTERCONDITION']._serialized_start=142
  _globals['_COLUMNFILTERCONDITION']._serialized_end=271
  _globals['_TABLEFILTER']._serialized_start=273
  _globals['_TABLEFILTER']._serialized_end=355
  _globals['_QUERY']._serialized_start=358
  _globals['_QUERY']._serialized_end=501
  _globals['_QUERYRESULT']._serialized_start=503
  _globals['_QUERYRESULT']._serialized_end=551
  _globals['_QUERYROW']._serialized_start=553
  _globals['_QUERYROW']._serialized_end=628
# @@protoc_insertion_point(module_scope)
