# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rpc_pb2 as rpc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LaoflchDbStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/laoflchdb.rpc.LaoflchDb/Get',
                request_serializer=rpc__pb2.GetRequest.SerializeToString,
                response_deserializer=rpc__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/laoflchdb.rpc.LaoflchDb/Put',
                request_serializer=rpc__pb2.PutRequest.SerializeToString,
                response_deserializer=rpc__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/laoflchdb.rpc.LaoflchDb/Delete',
                request_serializer=rpc__pb2.DeleteRequest.SerializeToString,
                response_deserializer=rpc__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.CreateTable = channel.unary_unary(
                '/laoflchdb.rpc.LaoflchDb/CreateTable',
                request_serializer=rpc__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=rpc__pb2.CreateTableResponse.FromString,
                _registered_method=True)
        self.ListTables = channel.unary_unary(
                '/laoflchdb.rpc.LaoflchDb/ListTables',
                request_serializer=rpc__pb2.ListTablesRequest.SerializeToString,
                response_deserializer=rpc__pb2.ListTablesResponse.FromString,
                _registered_method=True)
        self.GetTableMeta = channel.unary_unary(
                '/laoflchdb.rpc.LaoflchDb/GetTableMeta',
                request_serializer=rpc__pb2.GetTableMetaRequest.SerializeToString,
                response_deserializer=rpc__pb2.GetTableMetaResponse.FromString,
                _registered_method=True)


class LaoflchDbServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """KV 操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        """表管理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTableMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LaoflchDbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=rpc__pb2.GetRequest.FromString,
                    response_serializer=rpc__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=rpc__pb2.PutRequest.FromString,
                    response_serializer=rpc__pb2.PutResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=rpc__pb2.DeleteRequest.FromString,
                    response_serializer=rpc__pb2.DeleteResponse.SerializeToString,
            ),
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=rpc__pb2.CreateTableRequest.FromString,
                    response_serializer=rpc__pb2.CreateTableResponse.SerializeToString,
            ),
            'ListTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTables,
                    request_deserializer=rpc__pb2.ListTablesRequest.FromString,
                    response_serializer=rpc__pb2.ListTablesResponse.SerializeToString,
            ),
            'GetTableMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTableMeta,
                    request_deserializer=rpc__pb2.GetTableMetaRequest.FromString,
                    response_serializer=rpc__pb2.GetTableMetaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laoflchdb.rpc.LaoflchDb', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laoflchdb.rpc.LaoflchDb', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LaoflchDb(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.rpc.LaoflchDb/Get',
            rpc__pb2.GetRequest.SerializeToString,
            rpc__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.rpc.LaoflchDb/Put',
            rpc__pb2.PutRequest.SerializeToString,
            rpc__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.rpc.LaoflchDb/Delete',
            rpc__pb2.DeleteRequest.SerializeToString,
            rpc__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.rpc.LaoflchDb/CreateTable',
            rpc__pb2.CreateTableRequest.SerializeToString,
            rpc__pb2.CreateTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.rpc.LaoflchDb/ListTables',
            rpc__pb2.ListTablesRequest.SerializeToString,
            rpc__pb2.ListTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTableMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.rpc.LaoflchDb/GetTableMeta',
            rpc__pb2.GetTableMetaRequest.SerializeToString,
            rpc__pb2.GetTableMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
