# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\rlaoflchdb.rpc\"(\n\nGetRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"+\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\"7\n\nPutRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\"\r\n\x0bPutResponse\"+\n\rDeleteRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"\x10\n\x0e\x44\x65leteResponse\"S\n\x12\x43reateTableRequest\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12)\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\x18.laoflchdb.rpc.ColumnDef\"+\n\tColumnDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63ol_type\x18\x02 \x01(\r\"\'\n\x13\x43reateTableResponse\x12\x10\n\x08table_id\x18\x01 \x01(\t\"\x13\n\x11ListTablesRequest\"$\n\x12ListTablesResponse\x12\x0e\n\x06tables\x18\x01 \x03(\t\")\n\x13GetTableMetaRequest\x12\x12\n\ntable_name\x18\x01 \x01(\t\"b\n\x14GetTableMetaResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x10\n\x08table_id\x18\x02 \x01(\t\x12\x12\n\ntable_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63olumn_count\x18\x04 \x01(\r2\xd0\x03\n\tLaoflchDb\x12<\n\x03Get\x12\x19.laoflchdb.rpc.GetRequest\x1a\x1a.laoflchdb.rpc.GetResponse\x12<\n\x03Put\x12\x19.laoflchdb.rpc.PutRequest\x1a\x1a.laoflchdb.rpc.PutResponse\x12\x45\n\x06\x44\x65lete\x12\x1c.laoflchdb.rpc.DeleteRequest\x1a\x1d.laoflchdb.rpc.DeleteResponse\x12T\n\x0b\x43reateTable\x12!.laoflchdb.rpc.CreateTableRequest\x1a\".laoflchdb.rpc.CreateTableResponse\x12Q\n\nListTables\x12 .laoflchdb.rpc.ListTablesRequest\x1a!.laoflchdb.rpc.ListTablesResponse\x12W\n\x0cGetTableMeta\x12\".laoflchdb.rpc.GetTableMetaRequest\x1a#.laoflchdb.rpc.GetTableMetaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=28
  _globals['_GETREQUEST']._serialized_end=68
  _globals['_GETRESPONSE']._serialized_start=70
  _globals['_GETRESPONSE']._serialized_end=113
  _globals['_PUTREQUEST']._serialized_start=115
  _globals['_PUTREQUEST']._serialized_end=170
  _globals['_PUTRESPONSE']._serialized_start=172
  _globals['_PUTRESPONSE']._serialized_end=185
  _globals['_DELETEREQUEST']._serialized_start=187
  _globals['_DELETEREQUEST']._serialized_end=230
  _globals['_DELETERESPONSE']._serialized_start=232
  _globals['_DELETERESPONSE']._serialized_end=248
  _globals['_CREATETABLEREQUEST']._serialized_start=250
  _globals['_CREATETABLEREQUEST']._serialized_end=333
  _globals['_COLUMNDEF']._serialized_start=335
  _globals['_COLUMNDEF']._serialized_end=378
  _globals['_CREATETABLERESPONSE']._serialized_start=380
  _globals['_CREATETABLERESPONSE']._serialized_end=419
  _globals['_LISTTABLESREQUEST']._serialized_start=421
  _globals['_LISTTABLESREQUEST']._serialized_end=440
  _globals['_LISTTABLESRESPONSE']._serialized_start=442
  _globals['_LISTTABLESRESPONSE']._serialized_end=478
  _globals['_GETTABLEMETAREQUEST']._serialized_start=480
  _globals['_GETTABLEMETAREQUEST']._serialized_end=521
  _globals['_GETTABLEMETARESPONSE']._serialized_start=523
  _globals['_GETTABLEMETARESPONSE']._serialized_end=621
  _globals['_LAOFLCHDB']._serialized_start=624
  _globals['_LAOFLCHDB']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
