# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_summarize.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'text_summarize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14text_summarize.proto\x12\x18laoflchdb.text_summarize\"\x89\x01\n\x10SummarizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0ftarget_language\x18\x02 \x01(\t\x12\x12\n\nmax_length\x18\x03 \x01(\x05\x12\x12\n\nmin_length\x18\x04 \x01(\x05\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x11\n\tnum_beams\x18\x06 \x01(\x05\"\xaa\x01\n\x11SummarizeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x19\n\x11\x64\x65tected_language\x18\x04 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x05 \x01(\x03\x12\x14\n\x0cinput_length\x18\x06 \x01(\x05\x12\x15\n\routput_length\x18\x07 \x01(\x05\"\x14\n\x12HealthCheckRequest\"N\n\x13HealthCheckResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x14\n\x0cmodel_status\x18\x03 \x01(\t2\xe8\x01\n\x14TextSummarizeService\x12\x64\n\tSummarize\x12*.laoflchdb.text_summarize.SummarizeRequest\x1a+.laoflchdb.text_summarize.SummarizeResponse\x12j\n\x0bHealthCheck\x12,.laoflchdb.text_summarize.HealthCheckRequest\x1a-.laoflchdb.text_summarize.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_summarize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARIZEREQUEST']._serialized_start=51
  _globals['_SUMMARIZEREQUEST']._serialized_end=188
  _globals['_SUMMARIZERESPONSE']._serialized_start=191
  _globals['_SUMMARIZERESPONSE']._serialized_end=361
  _globals['_HEALTHCHECKREQUEST']._serialized_start=363
  _globals['_HEALTHCHECKREQUEST']._serialized_end=383
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=385
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=463
  _globals['_TEXTSUMMARIZESERVICE']._serialized_start=466
  _globals['_TEXTSUMMARIZESERVICE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
