# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import text_summarize_pb2 as text__summarize__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in text_summarize_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextSummarizeServiceStub(object):
    """文本摘要服务（基于 candle + T5/Flan-T5）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Summarize = channel.unary_unary(
                '/laoflchdb.text_summarize.TextSummarizeService/Summarize',
                request_serializer=text__summarize__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=text__summarize__pb2.SummarizeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/laoflchdb.text_summarize.TextSummarizeService/HealthCheck',
                request_serializer=text__summarize__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=text__summarize__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TextSummarizeServiceServicer(object):
    """文本摘要服务（基于 candle + T5/Flan-T5）
    """

    def Summarize(self, request, context):
        """生成文本摘要
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextSummarizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=text__summarize__pb2.SummarizeRequest.FromString,
                    response_serializer=text__summarize__pb2.SummarizeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=text__summarize__pb2.HealthCheckRequest.FromString,
                    response_serializer=text__summarize__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'laoflchdb.text_summarize.TextSummarizeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('laoflchdb.text_summarize.TextSummarizeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextSummarizeService(object):
    """文本摘要服务（基于 candle + T5/Flan-T5）
    """

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.text_summarize.TextSummarizeService/Summarize',
            text__summarize__pb2.SummarizeRequest.SerializeToString,
            text__summarize__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/laoflchdb.text_summarize.TextSummarizeService/HealthCheck',
            text__summarize__pb2.HealthCheckRequest.SerializeToString,
            text__summarize__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
